"""Public runtime API through the Milestone-A task-resource boundary."""

from .confinement import ConfinementLevel, allows_real_engine
from .credentials import (
    CredentialContext,
    EngineCredentialProvider,
    NullCredentialProvider,
    SyntheticCredentialProvider,
)
from .diagnostics import DiagnosticCapture
from .dto import (
    AggregatePaperEvidenceInvocation,
    AssessClaimInput,
    AssessClaimInvocation,
    AssessEvidenceInvocation,
    AuditPropositionInput,
    AuditPropositionInvocation,
    AuditRenderedSentenceInvocation,
    CandidateClaimProposal,
    ClaimAssessmentProposal,
    CorpusChallengerInvocation,
    DiscoveryProposalBundle,
    GenerateCandidateClaimsInput,
    GenerateCandidateClaimsInvocation,
    GeneratePropositionsInvocation,
    GenerateRetrievalQueriesInvocation,
    ParseDeepResearchInput,
    ParseDeepResearchInvocation,
    RenderProseInvocation,
    ReviseClaimInvocation,
    SemanticAuditProposal,
    ThemeProposal,
    ValidateFinalClaimInvocation,
)
from .engine import AgentEngine, MockEngine, MockResponse
from .execution_inventory import ExecutionFileRecord
from .kernel import ProjectRuntime
from .records import (
    FALLBACK_OUTCOMES,
    MEDIA_EXTENSIONS,
    AgentResult,
    AgentTask,
    AttemptFailure,
    AttemptFailureStage,
    AttemptOutcome,
    ProjectContext,
    ResourceLimitCode,
    ResourceProvenance,
    ResourceSourceDependency,
    ResourceValidationError,
    RuntimeConfig,
    RuntimeResult,
    SnapshottedResource,
    SnapshotSourceChangedError,
    TaskAttemptRecord,
    TaskProvenance,
    TaskResourceRequest,
    TaskSpec,
    TaskSpecNotExecutableError,
    TaskType,
    allocate_resource_id,
    build_resource_requests,
    fallback_allowed,
    resource_destination,
    validate_resource_requests,
)
from .repository import (
    CrashPoint,
    GenerationStore,
    InjectedCrash,
    PromotionPayload,
    StaleSnapshotError,
)
from .specs import TASK_SPECS, executable_task_types, validate_task_spec_executable
from .state import RepositorySnapshot
from .subprocess import (
    QUOTA_EXEMPT_ROOTS,
    WRITABLE_QUOTA_ROOTS,
    SubprocessPolicy,
    deterministic_test_policy,
    primary_attempt_outcome,
    writable_quota_applies,
)
from .tasks import BundleIntegrityError, TaskWorkspace

__all__ = [
    "AgentEngine",
    "AgentResult",
    "AgentTask",
    "AggregatePaperEvidenceInvocation",
    "AssessClaimInput",
    "AssessClaimInvocation",
    "AssessEvidenceInvocation",
    "AttemptFailure",
    "AttemptFailureStage",
    "AttemptOutcome",
    "AuditPropositionInput",
    "AuditPropositionInvocation",
    "AuditRenderedSentenceInvocation",
    "BundleIntegrityError",
    "CandidateClaimProposal",
    "ClaimAssessmentProposal",
    "ConfinementLevel",
    "CorpusChallengerInvocation",
    "CrashPoint",
    "CredentialContext",
    "DiagnosticCapture",
    "DiscoveryProposalBundle",
    "EngineCredentialProvider",
    "ExecutionFileRecord",
    "FALLBACK_OUTCOMES",
    "GenerateCandidateClaimsInput",
    "GenerateCandidateClaimsInvocation",
    "GeneratePropositionsInvocation",
    "GenerateRetrievalQueriesInvocation",
    "GenerationStore",
    "InjectedCrash",
    "MEDIA_EXTENSIONS",
    "MockEngine",
    "MockResponse",
    "NullCredentialProvider",
    "ParseDeepResearchInput",
    "ParseDeepResearchInvocation",
    "ProjectContext",
    "ProjectRuntime",
    "PromotionPayload",
    "QUOTA_EXEMPT_ROOTS",
    "RenderProseInvocation",
    "RepositorySnapshot",
    "ResourceLimitCode",
    "ResourceProvenance",
    "ResourceSourceDependency",
    "ResourceValidationError",
    "ReviseClaimInvocation",
    "RuntimeConfig",
    "RuntimeResult",
    "SemanticAuditProposal",
    "SnapshottedResource",
    "SnapshotSourceChangedError",
    "StaleSnapshotError",
    "SubprocessPolicy",
    "SyntheticCredentialProvider",
    "TASK_SPECS",
    "TaskAttemptRecord",
    "TaskProvenance",
    "TaskResourceRequest",
    "TaskSpec",
    "TaskSpecNotExecutableError",
    "TaskType",
    "TaskWorkspace",
    "ThemeProposal",
    "ValidateFinalClaimInvocation",
    "WRITABLE_QUOTA_ROOTS",
    "allocate_resource_id",
    "allows_real_engine",
    "build_resource_requests",
    "deterministic_test_policy",
    "executable_task_types",
    "fallback_allowed",
    "primary_attempt_outcome",
    "resource_destination",
    "validate_resource_requests",
    "validate_task_spec_executable",
    "writable_quota_applies",
]
