"""Programmatic sandbox conformance suite and report contract (goal.md §6.1).

The report is generated by actually executing every required case through the
real :class:`SubprocessEngine` + :class:`BubblewrapExecutionBackend` path
against a throwaway review project in a fresh temporary directory — never by
trusting pytest results. The dedicated :mod:`vibereview.runtime.conformance_worker`
is the only worker; test helpers are never imported by shipped runtime code.

Case ids equal the pytest conformance test names so the report suite and the
pytest suite cannot drift apart.
"""

from __future__ import annotations

import json
import shutil
import socket
import tempfile
import threading
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

from .confinement import (
    CONFORMANCE_SUITE_VERSION,
    REQUIRED_CONFORMANCE_TESTS,
    ConfinementLevel,
    NetworkPolicy,
    SandboxProbeResult,
    SandboxProbeStatus,
    probe_sandbox_capabilities,
)
from .credentials import SyntheticCredentialProvider
from .dto import GenerateCandidateClaimsInvocation
from .execution import (
    BubblewrapExecutionBackend,
    LauncherConfiguration,
    SubprocessAgentResult,
    SubprocessEngine,
)
from .hashing import hash_json
from .kernel import ProjectRuntime
from .records import AttemptOutcome, RuntimeModel, Sha256, TaskType
from .subprocess import deterministic_test_policy

CONFORMANCE_WORKER_PATH = Path(__file__).resolve().parent / "conformance_worker.py"

_LOOPBACK_RESPONSE = "vibereview-conformance-loopback"
_HOST_CANARY_CONTENT = "vibereview-conformance-host-canary"
_CREDENTIAL_TOKEN = "vibereview-conformance-credential-token"

_VALID_PROPOSAL = {
    "themes": [
        {
            "local_ref": "theme_1",
            "title": "Thermal management",
            "description": "Sandbox conformance fixture proposal",
            "origin": "generated",
            "parent_ref": None,
        }
    ],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "theme_1",
            "candidate_claim": "Preheating changes residual stress.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}


class SandboxConformanceCaseResult(RuntimeModel):
    """Retained record of one executed conformance case (goal.md §6.1)."""

    case_id: str
    passed: bool

    started_at: str
    finished_at: str

    diagnostic: str | None
    attempt_outcome: AttemptOutcome | None

    stdout_hash: Sha256 | None
    stderr_hash: Sha256 | None


class SandboxConformanceReport(RuntimeModel):
    """Executed conformance evidence for one host and profile (goal.md §6.1)."""

    suite_version: str

    backend_name: str
    confinement_level: ConfinementLevel
    network_policy: NetworkPolicy

    probe: SandboxProbeResult
    cases: tuple[SandboxConformanceCaseResult, ...]

    required_case_ids: tuple[str, ...]
    all_required_passed: bool

    report_hash: Sha256


def compute_conformance_report_hash(report: SandboxConformanceReport) -> str:
    """Canonical hash of the report payload (goal.md §6.1).

    Excluded-field pattern: the canonical payload is the full report
    serialization minus the ``report_hash`` field itself.
    """

    payload = report.model_dump(mode="json")
    payload.pop("report_hash")
    return hash_json(payload)


class _LoopbackServer:
    """Temporary loopback TCP server with a known one-shot response."""

    def __init__(self) -> None:
        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._socket.bind(("127.0.0.1", 0))
        self._socket.listen(4)
        self._socket.settimeout(0.2)
        self.connections_accepted = 0
        self._stopped = threading.Event()
        self._thread = threading.Thread(
            target=self._serve, name="vibereview-conformance-loopback", daemon=True
        )
        self._thread.start()

    @property
    def host(self) -> str:
        return "127.0.0.1"

    @property
    def port(self) -> int:
        return self._socket.getsockname()[1]

    def _serve(self) -> None:
        while not self._stopped.is_set():
            try:
                connection, _ = self._socket.accept()
            except (TimeoutError, OSError):
                continue
            with connection:
                self.connections_accepted += 1
                connection.sendall((_LOOPBACK_RESPONSE + "\n").encode("utf-8"))

    def close(self) -> None:
        self._stopped.set()
        self._socket.close()
        self._thread.join(timeout=2.0)


class _CaseContext:
    """Shared scaffolding for one executed conformance case."""

    def __init__(self, runtime: ProjectRuntime, host_root: Path, server: _LoopbackServer):
        self.runtime = runtime
        self.host_root = host_root
        self.server = server

    def run_case(
        self,
        case_id: str,
        *,
        modes: tuple[str, ...],
        network_policy: NetworkPolicy = NetworkPolicy.DENY,
        worker_config: dict | None = None,
        credential_provider: SyntheticCredentialProvider | None = None,
        evaluate: Callable[[AttemptOutcome, str, str, SubprocessAgentResult], str | None],
    ) -> SandboxConformanceCaseResult:
        started_at = datetime.now(UTC).isoformat()
        launcher = LauncherConfiguration(
            worker_script=CONFORMANCE_WORKER_PATH,
            worker_config=dict(worker_config or {}),
            proposal_payloads={
                "valid_proposal.json": json.dumps(_VALID_PROPOSAL).encode("utf-8")
            },
        )
        backend = BubblewrapExecutionBackend(launcher, network_policy=network_policy)
        engine = SubprocessEngine(
            name=f"conformance-{case_id}",
            worker_script=CONFORMANCE_WORKER_PATH,
            modes=modes,
            policy=deterministic_test_policy(),
            backend=backend,
            credential_provider=credential_provider,
        )
        result = self.runtime.run(
            TaskType.GENERATE_CANDIDATE_CLAIMS,
            GenerateCandidateClaimsInvocation(
                topic="sandbox conformance", existing_theme_ids=[]
            ),
            engines=[engine],
        )
        finished_at = datetime.now(UTC).isoformat()

        agent_result: SubprocessAgentResult | None = None
        if result.attempt_records:
            agent_result_path = (
                self.runtime.project_root / result.attempt_records[0].agent_result_path
            )
            if agent_result_path.is_file():
                agent_result = SubprocessAgentResult.model_validate_json(
                    agent_result_path.read_text(encoding="utf-8")
                )
        stdout_text = agent_result.stdout if agent_result is not None else ""
        stderr_text = agent_result.stderr if agent_result is not None else ""
        if agent_result is None:
            diagnostic: str | None = "no attempt record or agent result persisted"
        else:
            diagnostic = evaluate(result.outcome, stdout_text, stderr_text, agent_result)
        execution_report = agent_result.execution_report if agent_result is not None else None
        return SandboxConformanceCaseResult(
            case_id=case_id,
            passed=diagnostic is None,
            started_at=started_at,
            finished_at=finished_at,
            diagnostic=diagnostic,
            attempt_outcome=result.outcome,
            stdout_hash=(
                execution_report.stdout_capture.retained_redacted_hash
                if execution_report is not None
                else None
            ),
            stderr_hash=(
                execution_report.stderr_capture.retained_redacted_hash
                if execution_report is not None
                else None
            ),
        )


def _expect(outcome: AttemptOutcome, checks: tuple[tuple[bool, str], ...]) -> str | None:
    """None when the outcome is VALID and every check holds, else a diagnostic."""

    if outcome is not AttemptOutcome.VALID_SCIENTIFIC_RESULT:
        return f"attempt outcome is {outcome}, expected a valid scientific result"
    for holds, message in checks:
        if not holds:
            return message
    return None


def run_sandbox_conformance(
    *,
    network_policy: NetworkPolicy = NetworkPolicy.DENY,
    probe: SandboxProbeResult | None = None,
    bwrap_path: Path | str | None = None,
) -> SandboxConformanceReport:
    """Execute the required conformance cases and build the report (goal.md §6.1).

    The capability probe runs first; a non-USABLE probe means no execution
    and no qualification — the returned report carries the probe and an empty
    case list with ``all_required_passed=False``.
    """

    if probe is None:
        probe = probe_sandbox_capabilities(bwrap_path, network_policy=network_policy)

    cases: list[SandboxConformanceCaseResult] = []
    if probe.status is SandboxProbeStatus.USABLE:
        run_root = Path(tempfile.mkdtemp(prefix="vibereview-conformance-")).resolve()
        server = _LoopbackServer()
        try:
            runtime = ProjectRuntime.create(
                run_root / "project", project_name="sandbox-conformance"
            )
            context = _CaseContext(runtime, run_root, server)
            cases = _execute_all_cases(context)
        finally:
            server.close()
            shutil.rmtree(run_root, ignore_errors=True)

    executed_ids = {case.case_id for case in cases}
    if probe.status is SandboxProbeStatus.USABLE and executed_ids != set(
        REQUIRED_CONFORMANCE_TESTS
    ):
        raise RuntimeError(
            "conformance runner did not execute exactly the required cases: "
            f"missing={sorted(set(REQUIRED_CONFORMANCE_TESTS) - executed_ids)} "
            f"extra={sorted(executed_ids - set(REQUIRED_CONFORMANCE_TESTS))}"
        )

    all_required_passed = bool(cases) and all(case.passed for case in cases)
    report = SandboxConformanceReport(
        suite_version=CONFORMANCE_SUITE_VERSION,
        backend_name="bubblewrap",
        confinement_level=ConfinementLevel.OS_SANDBOX,
        network_policy=network_policy,
        probe=probe,
        cases=tuple(cases),
        required_case_ids=REQUIRED_CONFORMANCE_TESTS,
        all_required_passed=all_required_passed,
        report_hash="sha256:" + "0" * 64,
    )
    return report.model_copy(
        update={"report_hash": compute_conformance_report_hash(report)}
    )


def _execute_all_cases(context: _CaseContext) -> list[SandboxConformanceCaseResult]:
    cases: list[SandboxConformanceCaseResult] = []
    runtime = context.runtime

    canary_read = context.host_root / "host_canary.txt"
    canary_read.write_text(_HOST_CANARY_CONTENT, encoding="utf-8")
    cases.append(
        context.run_case(
            "test_canary_read_denied",
            modes=("canary_read", "valid"),
            worker_config={"canary_read_path": str(canary_read)},
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    ("CANARY_READ_ERROR=" in stdout, "canary read was not denied"),
                    (
                        _HOST_CANARY_CONTENT not in stdout,
                        "host canary content leaked into stdout",
                    ),
                ),
            ),
        )
    )

    canary_write = context.host_root / "host_pwn.txt"
    cases.append(
        context.run_case(
            "test_canary_write_denied",
            modes=("canary_write", "valid"),
            worker_config={"canary_write_path": str(canary_write)},
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    ("CANARY_WRITE_ERROR=" in stdout, "canary write was not denied"),
                    (not canary_write.exists(), "host canary file was created"),
                ),
            ),
        )
    )

    project_marker = runtime.project_root / "project.json"
    cases.append(
        context.run_case(
            "test_project_root_inaccessible",
            modes=("canary_read", "valid"),
            worker_config={"canary_read_path": str(project_marker)},
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    ("CANARY_READ_ERROR=" in stdout, "project root was readable"),
                ),
            ),
        )
    )

    provenance_files = sorted(
        runtime.project_root.glob("work/tasks/*/private/task_provenance.json")
    )
    private_target = (
        provenance_files[0]
        if provenance_files
        else runtime.project_root / "work" / "tasks" / "TASK0001" / "private" / "task_provenance.json"
    )
    cases.append(
        context.run_case(
            "test_task_private_inaccessible",
            modes=("canary_read", "valid"),
            worker_config={"canary_read_path": str(private_target)},
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    ("CANARY_READ_ERROR=" in stdout, "task private/ was readable"),
                ),
            ),
        )
    )

    cases.append(
        context.run_case(
            "test_bundle_immutable",
            modes=("bundle_write", "valid"),
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (("BUNDLE_WRITE_ERROR=" in stdout, "bundle accepted a write"),),
            ),
        )
    )

    cases.append(
        context.run_case(
            "test_authorized_output_and_scratch_writable",
            modes=("write_scratch", "valid"),
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    ("SCRATCH_WRITTEN=" in stdout, "scratch write marker missing"),
                    (
                        any(
                            entry.relative_path.as_posix() == "scratch/conformance_scratch.txt"
                            for entry in agent.execution_report.inventory
                        ),
                        "scratch file missing from the execution inventory",
                    ),
                ),
            ),
        )
    )

    context.server.connections_accepted = 0
    cases.append(
        context.run_case(
            "test_network_denied_under_deny",
            modes=("loopback_connect", "valid"),
            worker_config={
                "network_host": context.server.host,
                "network_port": context.server.port,
            },
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    ("NETWORK_DENIED=" in stdout, "loopback connect was not denied"),
                    (
                        context.server.connections_accepted == 0,
                        "loopback server received a connection under DENY",
                    ),
                ),
            ),
        )
    )

    cases.append(
        context.run_case(
            "test_host_network_profile_connects_to_loopback_server",
            modes=("loopback_connect", "valid"),
            network_policy=NetworkPolicy.HOST,
            worker_config={
                "network_host": context.server.host,
                "network_port": context.server.port,
            },
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    (
                        f"NETWORK_RESPONSE={_LOOPBACK_RESPONSE}" in stdout,
                        "loopback response not received under HOST",
                    ),
                ),
            ),
        )
    )

    cases.append(
        context.run_case(
            "test_intended_credential_readable",
            modes=("read_credentials", "valid"),
            credential_provider=SyntheticCredentialProvider(
                file_credentials={"conformance_token.txt": _CREDENTIAL_TOKEN}
            ),
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    (
                        "FILE_CREDENTIAL_NAME=conformance_token.txt" in stdout,
                        "intended credential was not visible",
                    ),
                ),
            ),
        )
    )

    cases.append(
        context.run_case(
            "test_credential_diagnostic_redaction",
            modes=("read_credentials", "valid"),
            credential_provider=SyntheticCredentialProvider(
                file_credentials={"conformance_token.txt": _CREDENTIAL_TOKEN}
            ),
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    ("[REDACTED]" in stdout, "credential content was not redacted"),
                    (
                        _CREDENTIAL_TOKEN not in stdout and _CREDENTIAL_TOKEN not in stderr,
                        "credential content leaked into retained diagnostics",
                    ),
                ),
            ),
        )
    )

    cases.append(
        context.run_case(
            "test_descendants_die_with_sandbox",
            modes=("valid", "spawn_descendants"),
            evaluate=lambda outcome, stdout, stderr, agent: _expect(
                outcome,
                (
                    (
                        agent.execution_report.quiescence is not None
                        and agent.execution_report.quiescence.quiescent
                        and agent.execution_report.quiescence.descendants_remaining == 0,
                        "descendants survived the confined attempt",
                    ),
                ),
            ),
        )
    )

    return cases
