"""Subprocess output-tree policy conformance (goal.md §6.9, §7.9, §7.12).

Runs the deterministic fake worker through the real subprocess boundary:

* an unexpected file under ``output/`` is an output-policy failure even when
  the composed proposal itself is valid (§7.9, §6.6 priority 4);
* unauthorized output content is never persisted under the attempt directory,
  and the execution root that held the only copy is deleted (§7.12);
* unsafe proposal file types (fifo/socket/symlink) are inventoried by type
  and relative path only — never opened, never hashed (§6.9);
* the execution inventory covers ``output/``/``scratch/``/``home/``/``tmp/``
  and never ``bundle/``/``launcher/``/``credentials/`` (§6.9, §7.10);
* ``allowed_output_files`` is configurable: a policy that permits an extra
  name accepts it, and any other name is still rejected (§6.7, §7.9).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from vibereview.runtime import (
    AttemptFailureStage,
    AttemptOutcome,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    SubprocessEngine,
    SubprocessExecutionResult,
    TaskAttemptRecord,
    TaskType,
    deterministic_test_policy,
)

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

# Must mirror tests/helpers/fake_agent.py exactly.
EXTRA_OUTPUT_PAYLOAD = b"unauthorized\n"
PERMITTED_SCRATCH_PAYLOAD = (b"permitted-scratch\n" * 57)[:1023] + b"\n"

_VALID_PROPOSAL = {
    "themes": [
        {
            "local_ref": "theme_1",
            "title": "Thermal management",
            "description": "Generated by deterministic fixture",
            "origin": "generated",
            "parent_ref": None,
        }
    ],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "theme_1",
            "candidate_claim": "Preheating changes residual stress.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}
VALID_PROPOSAL_BYTES = (
    json.dumps(_VALID_PROPOSAL, ensure_ascii=False, sort_keys=True) + "\n"
).encode("utf-8")


def _sha256(payload: bytes) -> str:
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def _engine(modes, *, name, policy=None, worker_config=None) -> SubprocessEngine:
    return SubprocessEngine(
        worker_script=WORKER,
        modes=tuple(modes),
        proposal_payloads={"valid_proposal.json": VALID_PROPOSAL_BYTES},
        name=name,
        worker_config=dict(worker_config or {}),
        policy=policy or deterministic_test_policy(),
    )


def _run(runtime: ProjectRuntime, engine: SubprocessEngine):
    return runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(
            topic="output-policy", existing_theme_ids=[]
        ),
        engines=[engine],
    )


def _attempt_dir(runtime: ProjectRuntime, record: TaskAttemptRecord) -> Path:
    return (
        runtime.project_root
        / "work"
        / "tasks"
        / record.task_id
        / "attempts"
        / record.attempt_id
    )


def _execution_report(
    runtime: ProjectRuntime, record: TaskAttemptRecord
) -> SubprocessExecutionResult:
    agent_result = json.loads(
        (_attempt_dir(runtime, record) / "agent_result.json").read_text(
            encoding="utf-8"
        )
    )
    return SubprocessExecutionResult.model_validate(agent_result["execution_report"])


def _inventory_index(report: SubprocessExecutionResult):
    return {entry.relative_path: entry for entry in report.inventory}


def _project_files(runtime: ProjectRuntime):
    return [
        path
        for path in sorted(runtime.project_root.rglob("*"))
        if path.is_file() and not path.is_symlink()
    ]


def test_extra_output_with_valid_proposal_is_output_policy_failure(tmp_path):
    """§7.9: anything beyond ``proposal.json`` under ``output/`` is rejected
    even when the proposal itself is valid (§6.6 priority 4)."""

    runtime = ProjectRuntime.create(tmp_path / "project", project_name="output-extra")
    result = _run(runtime, _engine(("valid", "extra_output"), name="output-extra"))

    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert result.generation is None
    assert runtime.store.current_generation() == 0

    (record,) = result.attempt_records
    assert record.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.output_hash is None

    (failure,) = record.detected_failures
    assert failure.code == "unexpected_output_file"
    assert failure.stage is AttemptFailureStage.OUTPUT_TREE
    assert failure.stage == "output_tree"
    assert failure.relative_path == Path("output") / "extra.txt"
    assert "extra.txt" in failure.message

    persisted = TaskAttemptRecord.model_validate_json(
        (_attempt_dir(runtime, record) / "attempt_record.json").read_text(
            encoding="utf-8"
        )
    )
    assert persisted == record

    report = _execution_report(runtime, record)
    assert report.output_policy_violated is True
    assert report.primary_outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    inventory = _inventory_index(report)
    assert inventory[Path("output") / "extra.txt"].file_type == "regular"
    assert inventory[Path("output") / "proposal.json"].file_type == "regular"

    # A failed attempt promotes nothing and retains no proposal artifact.
    task_dir = runtime.project_root / "work" / "tasks" / record.task_id
    assert not (_attempt_dir(runtime, record) / "proposal.json").exists()
    assert not (task_dir / "accepted" / "proposal.json").exists()


def test_unauthorized_output_content_is_not_persisted(tmp_path):
    """§7.12: unauthorized output contents are never retained; the execution
    root that held the only copy is deleted after the attempt."""

    runtime = ProjectRuntime.create(tmp_path / "project", project_name="output-leak")
    result = _run(runtime, _engine(("valid", "extra_output"), name="output-leak"))
    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    (record,) = result.attempt_records

    # Nothing the worker wrote into output/ — neither the unauthorized extra
    # file nor the valid proposal bytes of the rejected attempt — may appear
    # in any persisted file under the attempt directory or wider project.
    needles = (EXTRA_OUTPUT_PAYLOAD, VALID_PROPOSAL_BYTES)
    for path in _project_files(runtime):
        content = path.read_bytes()
        for needle in needles:
            assert needle not in content, f"worker output persisted in {path}"
    assert not list(runtime.project_root.rglob("extra.txt"))

    report = _execution_report(runtime, record)
    assert report.execution_root is not None
    assert not report.execution_root.exists()


@pytest.mark.parametrize(
    ("mode", "expected_code", "expected_type"),
    [
        ("proposal_fifo", "proposal_unsafe_type", "fifo"),
        ("proposal_socket", "proposal_unsafe_type", "socket"),
        ("proposal_symlink", "proposal_symlink", "symlink"),
    ],
)
def test_unsafe_proposal_types_are_inventoried_without_being_opened(
    tmp_path, mode, expected_code, expected_type
):
    """§7.8 + §6.9: fifo/socket/symlink proposals are output-policy failures;
    the inventory records their type and path only (never opened or hashed)."""

    runtime = ProjectRuntime.create(tmp_path / "project", project_name=f"unsafe-{mode}")
    result = _run(runtime, _engine((mode,), name=f"unsafe-{mode.replace('_', '-')}"))

    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert result.generation is None
    assert runtime.store.current_generation() == 0

    (record,) = result.attempt_records
    assert record.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    (failure,) = record.detected_failures
    assert failure.code == expected_code
    assert failure.stage is AttemptFailureStage.PROPOSAL_FILE
    assert failure.stage == "proposal_file"
    assert failure.relative_path == Path("output") / "proposal.json"

    report = _execution_report(runtime, record)
    assert report.output_policy_violated is True
    entry = _inventory_index(report)[Path("output") / "proposal.json"]
    assert entry.file_type == expected_type
    assert entry.size_bytes is None
    assert entry.content_hash is None


def test_inventory_covers_writable_roots_but_never_trusted_roots(tmp_path):
    """§6.9 + §7.10: the inventory spans output/scratch/home/tmp only;
    bundle/, launcher/ and credentials/ never appear in it."""

    runtime = ProjectRuntime.create(tmp_path / "project", project_name="inventory")
    result = _run(runtime, _engine(("permitted_scratch",), name="inventory-roots"))

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    (record,) = result.attempt_records
    assert record.accepted_attempt is True

    report = _execution_report(runtime, record)
    assert report.inventory, "execution inventory must not be empty"
    roots = {entry.relative_path.parts[0] for entry in report.inventory}
    assert roots <= {"output", "scratch", "home", "tmp"}
    assert {"output", "scratch", "home"} <= roots
    for entry in report.inventory:
        assert not entry.relative_path.is_absolute()
        assert not {"bundle", "launcher", "credentials"} & set(
            entry.relative_path.parts
        )

    inventory = _inventory_index(report)
    proposal_entry = inventory[Path("output") / "proposal.json"]
    assert proposal_entry.file_type == "regular"
    assert proposal_entry.size_bytes == len(VALID_PROPOSAL_BYTES)
    assert proposal_entry.content_hash == _sha256(VALID_PROPOSAL_BYTES)

    scratch_entry = inventory[Path("scratch") / "ok.txt"]
    assert scratch_entry.file_type == "regular"
    assert scratch_entry.size_bytes == len(PERMITTED_SCRATCH_PAYLOAD)
    assert scratch_entry.content_hash == _sha256(PERMITTED_SCRATCH_PAYLOAD)

    config_entry = inventory[Path("home") / ".config"]
    assert config_entry.file_type == "directory"
    assert config_entry.size_bytes is None
    assert config_entry.content_hash is None


def test_allowed_output_files_accepts_configured_extra_file(tmp_path):
    """§6.7/§7.9: a policy allowing ('proposal.json', 'notes.txt') accepts a
    worker that writes both; the run is VALID."""

    policy = deterministic_test_policy().model_copy(
        update={"allowed_output_files": ("proposal.json", "notes.txt")}
    )
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="allow-extra")
    result = _run(
        runtime,
        _engine(
            ("valid", "extra_output"),
            name="allow-extra",
            policy=policy,
            worker_config={"extra_output_name": "notes.txt"},
        ),
    )

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    assert runtime.store.current_generation() == 1

    (record,) = result.attempt_records
    assert record.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert record.detected_failures == ()
    assert record.accepted_attempt is True

    report = _execution_report(runtime, record)
    assert report.output_policy_violated is False
    notes_entry = _inventory_index(report)[Path("output") / "notes.txt"]
    assert notes_entry.file_type == "regular"
    assert notes_entry.size_bytes == len(EXTRA_OUTPUT_PAYLOAD)
    assert notes_entry.content_hash == _sha256(EXTRA_OUTPUT_PAYLOAD)

    assert (_attempt_dir(runtime, record) / "proposal.json").is_file()

    # Even an allowed extra output contributes only an inventory hash; its
    # content is never persisted (§7.12).
    for path in _project_files(runtime):
        assert EXTRA_OUTPUT_PAYLOAD not in path.read_bytes()


def test_allowed_output_files_still_rejects_unconfigured_name(tmp_path):
    """§7.9: widening ``allowed_output_files`` does not open the door to
    names the policy does not list."""

    policy = deterministic_test_policy().model_copy(
        update={"allowed_output_files": ("proposal.json", "notes.txt")}
    )
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="deny-extra")
    result = _run(
        runtime,
        _engine(
            ("valid", "extra_output"),
            name="deny-extra",
            policy=policy,
            worker_config={"extra_output_name": "other.txt"},
        ),
    )

    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert result.generation is None
    assert runtime.store.current_generation() == 0

    (record,) = result.attempt_records
    assert record.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    (failure,) = record.detected_failures
    assert failure.code == "unexpected_output_file"
    assert failure.stage is AttemptFailureStage.OUTPUT_TREE
    assert failure.relative_path == Path("output") / "other.txt"
