"""End-to-end §6.6 primary-outcome precedence through the B2 subprocess pipeline.

The deterministic fake worker (tests/helpers/fake_agent.py) composes defect
modes inside one attempt; the runner (runtime/execution.py) pre-classifies the
conditions it owns — process, resource-limit, workspace-integrity, output-tree
and proposal-file stages — through the frozen ``primary_attempt_outcome``
precedence, and the kernel adjudicates the remaining format → schema →
proposal-validation stages only when the runner reported
VALID_SCIENTIFIC_RESULT (kernel.py §6.6 handoff).

Consequences asserted here:

* runner-stage combos select exactly one primary outcome on the
  TaskAttemptRecord while every other safely detected condition is retained in
  ``detected_failures`` with its code/stage;
* a co-present kernel-stage defect (a malformed proposal next to tampering or
  unauthorized output) is never adjudicated once a higher-precedence runner
  condition fired — the malformed bytes are retained and hashed in the
  execution inventory instead of appearing in ``detected_failures``;
* kernel stages keep their own precedence (format before schema before
  proposal validation);
* a valid proposal and a valid REJECT are VALID_SCIENTIFIC_RESULT and never
  fallback-eligible;
* repeating one combo run yields an identical outcome projection.

All tests run the real subprocess machinery (TemporaryWorkspaceBackend,
TEST_ONLY); none is an external-engine test.
"""

from __future__ import annotations

import json
from pathlib import Path

from vibereview.runtime import (
    AssessClaimInvocation,
    AttemptFailureStage,
    AttemptOutcome,
    ClaimAssessmentProposal,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    RepositorySnapshot,
    ResourceLimitCode,
    RuntimeResult,
    SubprocessEngine,
    TaskAttemptRecord,
    TaskType,
    deterministic_test_policy,
    fallback_allowed,
)
from vibereview.runtime.hashing import hash_bytes

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

# Mirrors tests/helpers/fake_agent.py MALFORMED_JSON_PAYLOAD.
MALFORMED_JSON_PAYLOAD = b'{"this is not json'

VALID_DISCOVERY_PROPOSAL = json.dumps(
    {
        "themes": [
            {
                "local_ref": "theme_1",
                "title": "Thermal management",
                "description": "Generated by deterministic fixture",
                "origin": "generated",
                "parent_ref": None,
            }
        ],
        "claims": [
            {
                "local_ref": "claim_1",
                "theme_ref": "theme_1",
                "candidate_claim": "Preheating changes residual stress.",
                "origin": "generated",
                "origin_refs": [],
            }
        ],
    }
).encode("utf-8")

SCHEMA_INVALID_PAYLOAD = b'{"unexpected": true}\n'

# Schema-valid discovery proposal that proposal validation rejects (the claim
# references a theme that does not exist).
TASK_INVALID_PAYLOAD = json.dumps(
    {
        "themes": [],
        "claims": [
            {
                "local_ref": "claim_1",
                "theme_ref": "unknown_theme",
                "candidate_claim": "Claim",
                "origin": "generated",
                "origin_refs": [],
            }
        ],
    }
).encode("utf-8")


def _engine(
    name: str,
    modes: tuple[str, ...],
    *,
    payloads: dict[str, bytes] | None = None,
    stretch_monitor_interval: bool = False,
) -> SubprocessEngine:
    policy = deterministic_test_policy()
    if stretch_monitor_interval:
        # Stretch the mid-run monitor interval past the worker's lifetime so a
        # quota breach is adjudicated by the unconditional post-exit scan; the
        # process exit status is then also observed and retained, which makes
        # the simultaneously-detected failure set deterministic.
        policy = policy.model_copy(
            update={"writable_tree_scan_interval_seconds": 30.0}
        )
    return SubprocessEngine(
        worker_script=WORKER,
        modes=modes,
        proposal_payloads=dict(payloads or {}),
        name=name,
        policy=policy,
    )


def _run_discovery(
    runtime: ProjectRuntime, engines: list[SubprocessEngine]
) -> RuntimeResult:
    return runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="precedence", existing_theme_ids=[]),
        engines=engines,
    )


def _execution_report(runtime: ProjectRuntime, record: TaskAttemptRecord) -> dict:
    agent_result = json.loads(
        (runtime.project_root / record.agent_result_path).read_text(encoding="utf-8")
    )
    return agent_result["execution_report"]


def _inventory_entry(report: dict, relative_path: str) -> dict:
    for entry in report["inventory"]:
        if entry["relative_path"] == relative_path:
            return entry
    raise AssertionError(f"execution inventory lacks {relative_path}")


def _failure_triples(record: TaskAttemptRecord) -> list[tuple]:
    return [
        (failure.code, failure.stage, failure.relative_path)
        for failure in record.detected_failures
    ]


def _attempt_dir(runtime: ProjectRuntime, record: TaskAttemptRecord) -> Path:
    return (
        runtime.project_root
        / "work"
        / "tasks"
        / record.task_id
        / "attempts"
        / record.attempt_id
    )


def _persisted_record(runtime: ProjectRuntime, record: TaskAttemptRecord) -> None:
    persisted = TaskAttemptRecord.model_validate_json(
        (_attempt_dir(runtime, record) / "attempt_record.json").read_text(
            encoding="utf-8"
        )
    )
    assert persisted == record


def _assert_failed_run_preserves_state(
    runtime: ProjectRuntime, result: RuntimeResult, generation_before: int
) -> None:
    assert result.generation is None
    assert result.transition is None
    assert runtime.store.current_generation() == generation_before


def test_bundle_tampering_with_malformed_proposal_is_workspace_integrity_failure(
    tmp_path,
):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="integrity")
    generation_before = runtime.store.current_generation()
    engine = _engine("tamper-malformed", ("tamper_instructions", "malformed_json"))
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    assert fallback_allowed(record.outcome)
    # The runner-stage condition is retained. §6.6 selects exactly one primary
    # outcome, so the kernel format stage never adjudicates the malformed
    # proposal once workspace integrity has fired.
    assert _failure_triples(record) == [
        (
            "bundle_integrity_mismatch",
            AttemptFailureStage.WORKSPACE,
            Path("bundle"),
        ),
    ]
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.validation_errors
    _persisted_record(runtime, record)

    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    assert report["exit_code"] == 0
    assert report["timed_out"] is False
    assert report["bundle_modified"] is True
    assert report["output_policy_violated"] is False
    assert report["resource_limit_breached"] is False
    # The co-present malformed proposal is retained as hashed inventory
    # evidence rather than as a detected failure.
    proposal = _inventory_entry(report, "output/proposal.json")
    assert proposal["file_type"] == "regular"
    assert proposal["content_hash"] == hash_bytes(MALFORMED_JSON_PAYLOAD)

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_unauthorized_output_with_malformed_proposal_is_output_policy_failure(
    tmp_path,
):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="policy")
    generation_before = runtime.store.current_generation()
    engine = _engine("extra-malformed", ("extra_output", "malformed_json"))
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert fallback_allowed(record.outcome)
    assert _failure_triples(record) == [
        (
            "unexpected_output_file",
            AttemptFailureStage.OUTPUT_TREE,
            Path("output/extra.txt"),
        ),
    ]
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.validation_errors
    _persisted_record(runtime, record)

    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert report["exit_code"] == 0
    assert report["output_policy_violated"] is True
    assert report["bundle_modified"] is False
    assert report["resource_limit_breached"] is False
    extra = _inventory_entry(report, "output/extra.txt")
    assert extra["file_type"] == "regular"
    proposal = _inventory_entry(report, "output/proposal.json")
    assert proposal["file_type"] == "regular"
    assert proposal["content_hash"] == hash_bytes(MALFORMED_JSON_PAYLOAD)

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_resource_limit_breach_outranks_nonzero_exit(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="resource")
    generation_before = runtime.store.current_generation()
    engine = _engine(
        "rl-nonzero",
        ("large_scratch_file", "nonzero"),
        stretch_monitor_interval=True,
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert fallback_allowed(record.outcome)
    # Both simultaneously detected conditions are retained: the nonzero exit
    # at the process stage and the quota breach at the resource-limit stage,
    # plus the missing proposal the failed worker never wrote.
    assert _failure_triples(record) == [
        ("process_nonzero_exit", AttemptFailureStage.PROCESS, None),
        (
            ResourceLimitCode.MAX_WRITABLE_SINGLE_FILE_BYTES,
            AttemptFailureStage.RESOURCE_LIMIT,
            Path("scratch/big.bin"),
        ),
        (
            "proposal_missing",
            AttemptFailureStage.PROPOSAL_FILE,
            Path("output/proposal.json"),
        ),
    ]
    assert record.accepted_attempt is False
    assert record.validation_errors
    _persisted_record(runtime, record)

    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert report["exit_code"] == 3
    assert report["timed_out"] is False
    assert report["resource_limit_breached"] is True
    assert report["bundle_modified"] is False

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_resource_limit_breach_outranks_every_simultaneous_condition(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="outrank")
    generation_before = runtime.store.current_generation()
    engine = _engine(
        "rl-all",
        ("large_scratch_file", "tamper_instructions", "extra_output", "nonzero"),
        stretch_monitor_interval=True,
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert fallback_allowed(record.outcome)
    # Process, workspace-integrity, output-tree and proposal-file conditions
    # are all detected and retained; the resource-limit breach still wins the
    # single primary outcome.
    assert _failure_triples(record) == [
        ("process_nonzero_exit", AttemptFailureStage.PROCESS, None),
        (
            ResourceLimitCode.MAX_WRITABLE_SINGLE_FILE_BYTES,
            AttemptFailureStage.RESOURCE_LIMIT,
            Path("scratch/big.bin"),
        ),
        (
            "bundle_integrity_mismatch",
            AttemptFailureStage.WORKSPACE,
            Path("bundle"),
        ),
        (
            "unexpected_output_file",
            AttemptFailureStage.OUTPUT_TREE,
            Path("output/extra.txt"),
        ),
        (
            "proposal_missing",
            AttemptFailureStage.PROPOSAL_FILE,
            Path("output/proposal.json"),
        ),
    ]
    assert {failure.stage for failure in record.detected_failures} == {
        AttemptFailureStage.PROCESS,
        AttemptFailureStage.RESOURCE_LIMIT,
        AttemptFailureStage.WORKSPACE,
        AttemptFailureStage.OUTPUT_TREE,
        AttemptFailureStage.PROPOSAL_FILE,
    }
    _persisted_record(runtime, record)

    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert report["exit_code"] == 3
    assert report["resource_limit_breached"] is True
    assert report["bundle_modified"] is True
    assert report["output_policy_violated"] is True

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_bundle_tampering_with_nonzero_exit_is_execution_failure(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="execution")
    generation_before = runtime.store.current_generation()
    engine = _engine("tamper-nonzero", ("tamper_instructions", "nonzero"))
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_EXECUTION_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    # Execution failure outranks the simultaneously detected bundle tampering
    # (§6.6: execution_failed precedes bundle_modified).
    assert record.outcome is AttemptOutcome.ENGINE_EXECUTION_FAILURE
    assert fallback_allowed(record.outcome)
    assert _failure_triples(record) == [
        ("process_nonzero_exit", AttemptFailureStage.PROCESS, None),
        (
            "bundle_integrity_mismatch",
            AttemptFailureStage.WORKSPACE,
            Path("bundle"),
        ),
        (
            "proposal_missing",
            AttemptFailureStage.PROPOSAL_FILE,
            Path("output/proposal.json"),
        ),
    ]
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.validation_errors
    _persisted_record(runtime, record)

    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == AttemptOutcome.ENGINE_EXECUTION_FAILURE
    assert report["exit_code"] == 3
    assert report["timed_out"] is False
    assert report["bundle_modified"] is True
    assert report["resource_limit_breached"] is False

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_nonzero_exit_discards_otherwise_valid_proposal(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="nonzero")
    generation_before = runtime.store.current_generation()
    engine = _engine(
        "nonzero-valid",
        ("nonzero", "valid"),
        payloads={"valid_proposal.json": VALID_DISCOVERY_PROPOSAL},
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_EXECUTION_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_EXECUTION_FAILURE
    assert fallback_allowed(record.outcome)
    assert _failure_triples(record) == [
        ("process_nonzero_exit", AttemptFailureStage.PROCESS, None),
    ]
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    _persisted_record(runtime, record)

    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == AttemptOutcome.ENGINE_EXECUTION_FAILURE
    assert report["exit_code"] == 3
    assert report["timed_out"] is False
    # A schema-perfect proposal was imported and retained, yet cannot rescue
    # the failed process: the §6.6 primary outcome remains execution failure.
    assert report["proposal_format_invalid"] is False
    proposal = _inventory_entry(report, "output/proposal.json")
    assert proposal["file_type"] == "regular"
    assert proposal["content_hash"] == hash_bytes(VALID_DISCOVERY_PROPOSAL)

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_malformed_proposal_is_kernel_format_failure(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="format")
    generation_before = runtime.store.current_generation()
    engine = _engine("malformed", ("malformed_json",))
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_FORMAT_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_FORMAT_FAILURE
    assert fallback_allowed(record.outcome)
    # Kernel-stage failures carry their diagnostics in validation_errors and
    # the format/schema flags, not in detected_failures.
    assert record.detected_failures == ()
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.validation_errors

    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert report["exit_code"] == 0
    proposal = _inventory_entry(report, "output/proposal.json")
    assert proposal["content_hash"] == hash_bytes(MALFORMED_JSON_PAYLOAD)

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_schema_invalid_proposal_is_kernel_schema_failure(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="schema")
    generation_before = runtime.store.current_generation()
    engine = _engine(
        "schema",
        ("schema_invalid",),
        payloads={"schema_invalid_proposal.json": SCHEMA_INVALID_PAYLOAD},
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_SCHEMA_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_SCHEMA_FAILURE
    assert fallback_allowed(record.outcome)
    assert record.detected_failures == ()
    assert record.format_valid is True
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.validation_errors

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_task_invalid_proposal_is_kernel_proposal_validation_failure(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="taskinvalid")
    generation_before = runtime.store.current_generation()
    engine = _engine(
        "task-invalid",
        ("proposal_invalid",),
        payloads={"proposal_invalid_proposal.json": TASK_INVALID_PAYLOAD},
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_PROPOSAL_VALIDATION_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_PROPOSAL_VALIDATION_FAILURE
    assert fallback_allowed(record.outcome)
    assert record.detected_failures == ()
    assert record.format_valid is True
    assert record.schema_valid is True
    assert record.proposal_validation_valid is False
    assert record.accepted_attempt is False
    assert record.validation_errors

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_schema_stage_adjudicates_before_proposal_validation(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="stages")
    generation_before = runtime.store.current_generation()
    # The worker exercises both defect modes; the schema-invalid payload is
    # written last, so the kernel adjudicates that content. The schema stage
    # fires first and proposal validation is never evaluated.
    engine = _engine(
        "schema-over-proposal",
        ("proposal_invalid", "schema_invalid"),
        payloads={
            "proposal_invalid_proposal.json": TASK_INVALID_PAYLOAD,
            "schema_invalid_proposal.json": SCHEMA_INVALID_PAYLOAD,
        },
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_SCHEMA_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_SCHEMA_FAILURE
    assert record.detected_failures == ()
    assert record.format_valid is True
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.validation_errors

    report = _execution_report(runtime, record)
    proposal = _inventory_entry(report, "output/proposal.json")
    assert proposal["content_hash"] == hash_bytes(SCHEMA_INVALID_PAYLOAD)

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_format_stage_adjudicates_before_schema(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="formatfirst")
    generation_before = runtime.store.current_generation()
    # The malformed payload is written last; the kernel stops at the format
    # stage, so the schema stage never runs (schema_valid stays False without
    # schema validation having been attempted).
    engine = _engine(
        "format-over-schema",
        ("schema_invalid", "malformed_json"),
        payloads={"schema_invalid_proposal.json": SCHEMA_INVALID_PAYLOAD},
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is AttemptOutcome.ENGINE_FORMAT_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_FORMAT_FAILURE
    assert record.detected_failures == ()
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.accepted_attempt is False
    assert record.validation_errors

    report = _execution_report(runtime, record)
    proposal = _inventory_entry(report, "output/proposal.json")
    assert proposal["content_hash"] == hash_bytes(MALFORMED_JSON_PAYLOAD)

    _assert_failed_run_preserves_state(runtime, result, generation_before)


def test_valid_proposal_commits_without_fallback(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="valid")
    primary = _engine(
        "primary-valid",
        ("valid",),
        payloads={"valid_proposal.json": VALID_DISCOVERY_PROPOSAL},
    )
    fallback = _engine(
        "fallback-unused",
        ("valid",),
        payloads={"valid_proposal.json": VALID_DISCOVERY_PROPOSAL},
    )
    result = _run_discovery(runtime, [primary, fallback])

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert not fallback_allowed(result.outcome)
    assert result.generation == 1
    assert runtime.store.current_generation() == 1
    assert result.engine == "primary-valid"
    assert result.allocated_ids == {"theme_1": "T0001", "claim_1": "C0001"}
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert record.detected_failures == ()
    assert record.format_valid is True
    assert record.schema_valid is True
    assert record.proposal_validation_valid is True
    assert record.accepted_attempt is True
    assert record.validation_errors == []
    # The fallback engine was never attempted.
    attempts_dir = _attempt_dir(runtime, record).parent
    assert sorted(path.name for path in attempts_dir.iterdir()) == [
        "01-primary-valid"
    ]
    _, snapshot, _ = runtime.store.load_current()
    assert snapshot.candidate_claims[0].claim_id == "C0001"


def _snapshot_ready_for_claim_assessment(bundle_factory) -> RepositorySnapshot:
    bundle = bundle_factory()
    for name in (
        "claim_assessments",
        "final_claim_validations",
        "claim_packets",
        "proposition_records",
        "semantic_audits",
        "rendered_sentences",
        "rendered_sentence_audits",
    ):
        bundle[name] = []
    return RepositorySnapshot.model_validate(bundle)


def test_valid_reject_is_canonicalized_without_fallback(tmp_path, bundle_factory):
    snapshot = _snapshot_ready_for_claim_assessment(bundle_factory)
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="reject", initial_snapshot=snapshot
    )
    reject_payload = json.dumps(
        ClaimAssessmentProposal(
            claim_ref="C0001",
            aggregate_strength="low",
            evidence_sufficiency="insufficient",
            decision="REJECT",
            rejection_basis="insufficient_evidence",
            support_summary="Insufficient.",
            contradiction_summary="None.",
            qualification_summary="None.",
            reason="Evidence is insufficient.",
        ).model_dump(mode="json")
    ).encode("utf-8")
    primary = _engine(
        "reject-primary",
        ("valid",),
        payloads={"valid_proposal.json": reject_payload},
    )
    fallback = _engine(
        "reject-fallback",
        ("valid",),
        payloads={"valid_proposal.json": reject_payload},
    )
    result = runtime.run(
        TaskType.ASSESS_CLAIM,
        AssessClaimInvocation(
            claim_id="C0001", claim_paper_evidence_ids=["CPE-C0001-P0001"]
        ),
        engines=[primary, fallback],
    )

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert not fallback_allowed(result.outcome)
    assert result.generation == 1
    assert result.transition is not None
    assert result.transition.scientific_disposition == "REJECT"
    assert result.transition.canonicalized
    assert not result.transition.downstream_eligible
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert record.accepted_attempt is True
    assert record.detected_failures == ()
    attempts_dir = _attempt_dir(runtime, record).parent
    assert sorted(path.name for path in attempts_dir.iterdir()) == [
        "01-reject-primary"
    ]
    _, current, _ = runtime.store.load_current()
    assert current.claim_assessments[0].decision.value == "REJECT"
    assert current.claim_packets == ()


def test_combo_outcome_is_identical_across_repeated_runs(tmp_path):
    projections = []
    for label in ("first", "second"):
        runtime = ProjectRuntime.create(
            tmp_path / label / "project", project_name=label
        )
        engine = _engine(
            "tamper-malformed", ("tamper_instructions", "malformed_json")
        )
        result = _run_discovery(runtime, [engine])
        record = result.attempt_records[0]
        report = _execution_report(runtime, record)
        # Messages are excluded: they embed the random external execution-root
        # path. Everything the scientific contract exposes is compared.
        projections.append(
            (
                result.outcome,
                result.generation,
                record.attempt_id,
                record.engine,
                record.outcome,
                record.format_valid,
                record.schema_valid,
                record.proposal_validation_valid,
                record.accepted_attempt,
                _failure_triples(record),
                report["primary_outcome"],
                report["exit_code"],
                report["timed_out"],
                report["resource_limit_breached"],
                report["bundle_modified"],
                report["output_policy_violated"],
                report["proposal_format_invalid"],
            )
        )
    assert projections[0] == projections[1]
    assert projections[0][4] is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
