from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from vibereview.runtime import (
    AttemptOutcome,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    ResourceLimitCode,
    SubprocessEngine,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.resource_limits import scan_writable_roots
from vibereview.runtime.subprocess import SubprocessPolicy

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

VALID_PROPOSAL = {
    "themes": [
        {
            "local_ref": "theme_1",
            "title": "Thermal management",
            "description": "Generated by deterministic fixture",
            "origin": "generated",
            "parent_ref": None,
        }
    ],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "theme_1",
            "candidate_claim": "Preheating changes residual stress.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}


def test_directories_counted_towards_quota(tmp_path: Path):
    root = tmp_path / "exec-root"
    for d in ("output", "scratch", "home", "tmp"):
        (root / d).mkdir(parents=True)

    # Create 257 directories under scratch
    for i in range(257):
        (root / "scratch" / f"dir_{i:04d}").mkdir()

    policy = deterministic_test_policy().model_copy(update={"max_writable_entries": 256})
    breach = scan_writable_roots(root, policy)
    assert breach is not None
    assert breach.code == ResourceLimitCode.MAX_WRITABLE_ENTRY_COUNT
    assert "Writable entry count exceeded 256." in breach.message


def test_symlinks_counted_towards_quota(tmp_path: Path):
    root = tmp_path / "exec-root"
    for d in ("output", "scratch", "home", "tmp"):
        (root / d).mkdir(parents=True)

    target = root / "output" / "target.txt"
    target.write_text("dummy", encoding="utf-8")

    # Create 257 symlinks under scratch
    for i in range(257):
        (root / "scratch" / f"link_{i:04d}").symlink_to(target)

    policy = deterministic_test_policy().model_copy(update={"max_writable_entries": 256})
    breach = scan_writable_roots(root, policy)
    assert breach is not None
    assert breach.code == ResourceLimitCode.MAX_WRITABLE_ENTRY_COUNT


def test_mixed_entries_totaling_quota_breach(tmp_path: Path):
    root = tmp_path / "exec-root"
    for d in ("output", "scratch", "home", "tmp"):
        (root / d).mkdir(parents=True)

    # 100 regular files in output
    for i in range(100):
        (root / "output" / f"file_{i:03d}.txt").write_text("x", encoding="utf-8")

    # 100 directories in scratch
    for i in range(100):
        (root / "scratch" / f"dir_{i:03d}").mkdir()

    # 57 FIFOs in tmp
    for i in range(57):
        os.mkfifo(root / "tmp" / f"fifo_{i:03d}")

    # Total entries = 100 + 100 + 57 = 257
    policy = deterministic_test_policy().model_copy(update={"max_writable_entries": 256})
    breach = scan_writable_roots(root, policy)
    assert breach is not None
    assert breach.code == ResourceLimitCode.MAX_WRITABLE_ENTRY_COUNT


def test_large_immutable_bundle_with_more_than_quota_entries_permitted(tmp_path: Path):
    # A bundle with > 256 entries must not trigger quota breach
    root = tmp_path / "exec-root"
    for d in ("bundle", "output", "scratch", "home", "tmp"):
        (root / d).mkdir(parents=True)

    for i in range(300):
        (root / "bundle" / f"bundle_file_{i:04d}.txt").write_text("b", encoding="utf-8")

    (root / "output" / "proposal.json").write_text("{}", encoding="utf-8")

    policy = deterministic_test_policy().model_copy(update={"max_writable_entries": 256})
    breach = scan_writable_roots(root, policy)
    assert breach is None


def test_hard_link_conservative_counting(tmp_path: Path):
    root = tmp_path / "exec-root"
    for d in ("output", "scratch", "home", "tmp"):
        (root / d).mkdir(parents=True)

    file1 = root / "output" / "original.bin"
    # Write 100 bytes
    file1.write_bytes(b"A" * 100)

    # Hardlink
    file2 = root / "scratch" / "hardlink.bin"
    os.link(file1, file2)

    # Two entries should count as 2 entries, and total_bytes = 200 bytes
    # Test entry count limit = 1 -> breach
    policy_entry = deterministic_test_policy().model_copy(update={"max_writable_entries": 1})
    breach_entry = scan_writable_roots(root, policy_entry)
    assert breach_entry is not None
    assert breach_entry.code == ResourceLimitCode.MAX_WRITABLE_ENTRY_COUNT

    # Test tree bytes limit = 150 -> breach because apparent size is counted twice (100 + 100 = 200 > 150)
    policy_bytes = deterministic_test_policy().model_copy(
        update={"max_writable_entries": 10, "max_writable_tree_bytes": 150}
    )
    breach_bytes = scan_writable_roots(root, policy_bytes)
    assert breach_bytes is not None
    assert breach_bytes.code == ResourceLimitCode.MAX_WRITABLE_TREE_BYTES


def test_special_entries_counted_never_opened_or_followed(tmp_path: Path):
    root = tmp_path / "exec-root"
    for d in ("output", "scratch", "home", "tmp"):
        (root / d).mkdir(parents=True)

    fifo = root / "scratch" / "blocked.fifo"
    os.mkfifo(fifo)

    # If scan_writable_roots opened the FIFO, it would block forever.
    # It must return cleanly without blocking.
    policy = deterministic_test_policy()
    breach = scan_writable_roots(root, policy)
    assert breach is None
