"""Tests for credential leases, file credentials, and cleanup lifecycle (goal.md §7)."""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path
from typing import Any

import pytest

from vibereview.ids import Sha256
from vibereview.runtime import (
    AttemptOutcome,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    SubprocessAgentResult,
    SubprocessEngine,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.credentials import (
    CredentialContext,
    EngineCredentialProvider,
    NullCredentialProvider,
    SyntheticCredentialProvider,
)

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

VALID_PROPOSAL = {
    "themes": [
        {
            "local_ref": "theme_1",
            "title": "Thermal management",
            "description": "Generated by deterministic fixture",
            "origin": "generated",
            "parent_ref": None,
        }
    ],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "theme_1",
            "candidate_claim": "Preheating changes residual stress.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}


def _engine(
    name: str,
    *,
    modes: tuple[str, ...] = ("valid",),
    credential_provider: EngineCredentialProvider | None = None,
    worker_config: dict | None = None,
) -> SubprocessEngine:
    return SubprocessEngine(
        name=name,
        worker_script=WORKER,
        modes=modes,
        credential_provider=credential_provider,
        worker_config=worker_config,
        proposal_payloads={
            "valid_proposal.json": json.dumps(VALID_PROPOSAL).encode("utf-8")
        },
    )


def _init_runtime(tmp_path: Path) -> ProjectRuntime:
    return ProjectRuntime.create(tmp_path / "project", project_name="cred-test")


def _run_task(runtime: ProjectRuntime, engine: SubprocessEngine):
    return runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="Stress", existing_theme_ids=[]),
        engines=[engine],
    )


def test_parent_only_secret_absent_from_child_and_diagnostics(tmp_path: Path, monkeypatch):
    """Parent-only secret exists in parent environment but is absent from child (goal.md §7.6)."""
    parent_secret = "SUPER_SECRET_PARENT_VALUE_999"
    monkeypatch.setenv("VIBEREVIEW_PARENT_SECRET", parent_secret)

    engine = _engine("fake-parent-secret", modes=("parent_secret_probe", "valid"))
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    record = result.attempt_records[0]
    agent_result = SubprocessAgentResult.model_validate_json(
        (runtime.project_root / record.agent_result_path).read_text(encoding="utf-8")
    )
    assert "PARENT_SECRET=<absent>" in agent_result.stdout
    assert parent_secret not in agent_result.stdout
    assert parent_secret not in agent_result.stderr


def test_injected_secret_redacted_in_diagnostics(tmp_path: Path):
    """Provider injects secret -> child prints it -> diagnostic redacted (goal.md §7.6)."""
    injected_secret = "injected_token_xyz_888"
    provider = SyntheticCredentialProvider(
        secret_env={"VIBEREVIEW_INJECTED_SECRET": injected_secret}
    )
    engine = _engine("fake-injected", modes=("injected_secret_probe", "valid"), credential_provider=provider)
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    record = result.attempt_records[0]
    agent_result = SubprocessAgentResult.model_validate_json(
        (runtime.project_root / record.agent_result_path).read_text(encoding="utf-8")
    )
    assert injected_secret not in agent_result.stdout
    assert "INJECTED_SECRET=[REDACTED]" in agent_result.stdout


def test_split_secret_regression_redaction(tmp_path: Path):
    """Child writes secret across chunk/flush boundary -> complete secret redacted (goal.md §7.6)."""
    injected_secret = "SPLIT_SECRET_TOKEN_45678"
    provider = SyntheticCredentialProvider(
        secret_env={"VIBEREVIEW_INJECTED_SECRET": injected_secret}
    )
    engine = _engine("fake-split", modes=("split_secret_probe", "valid"), credential_provider=provider)
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    record = result.attempt_records[0]
    agent_result = SubprocessAgentResult.model_validate_json(
        (runtime.project_root / record.agent_result_path).read_text(encoding="utf-8")
    )
    assert injected_secret not in agent_result.stdout
    assert "[REDACTED]" in agent_result.stdout
    # Ensure partial fragments didn't escape
    half = len(injected_secret) // 2
    assert injected_secret[:half] not in agent_result.stdout.replace("[REDACTED]", "")


def test_file_credentials_permissions_and_read(tmp_path: Path):
    """File credentials have 0600 permissions, dir 0700, and child can read (goal.md §7.4, §7.6)."""
    secret_content = "KEY_FILE_CONTENT_777"
    provider = SyntheticCredentialProvider(
        file_credentials={"auth_key.pem": secret_content}
    )
    engine = _engine(
        "fake-file-cred",
        modes=("read_file_credential", "valid"),
        credential_provider=provider,
    )
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    record = result.attempt_records[0]
    agent_result = SubprocessAgentResult.model_validate_json(
        (runtime.project_root / record.agent_result_path).read_text(encoding="utf-8")
    )
    stdout = agent_result.stdout
    assert "FILE_CREDENTIAL_NAME=auth_key.pem" in stdout
    assert "FILE_CREDENTIAL_MODE=0o600" in stdout
    # The secret content was added to exact_redactions so it gets redacted when printed
    assert secret_content not in stdout
    assert "[REDACTED]" in stdout


@pytest.mark.parametrize("failing_mode", ["nonzero", "timeout", "tamper_input"])
def test_file_credentials_cleaned_up_after_failure(tmp_path: Path, failing_mode: str):
    """File credentials are removed on every execution path, including failures (goal.md §7.6)."""
    tracked_target: list[Path] = []

    class TrackedSyntheticProvider(SyntheticCredentialProvider):
        def prepare(self, engine_name: str, credentials_dir: Path):
            lease = super().prepare(engine_name, credentials_dir)
            tracked_target.extend(lease._staged_files)
            return lease

    provider = TrackedSyntheticProvider(
        file_credentials={"ephemeral.key": "some_secret_key_1234"}
    )
    policy = deterministic_test_policy().model_copy(update={"timeout_seconds": 1.0})
    engine = SubprocessEngine(
        name=f"fake-cleanup-{failing_mode}",
        worker_script=WORKER,
        modes=(failing_mode,),
        credential_provider=provider,
        policy=policy,
        worker_config={"timeout_sleep_seconds": 5},
    )
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is not AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert len(tracked_target) > 0
    for file_path in tracked_target:
        assert not file_path.exists()


def test_credential_cleanup_failure_fails_closed(tmp_path: Path):
    """Lease cleanup failure -> INTERNAL_RUNTIME_FAILURE, no proposal import, no fallback (goal.md §7.5)."""
    provider = SyntheticCredentialProvider(
        file_credentials={"key.pem": "sec"},
        fail_cleanup=True,
    )
    engine = _engine("fake-cleanup-fail", modes=("valid",), credential_provider=provider)
    fallback_engine = _engine("fake-fallback", modes=("valid",))

    runtime = ProjectRuntime.create(tmp_path / "project", project_name="cleanup-fail")
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="Stress", existing_theme_ids=[]),
        engines=[engine, fallback_engine],
    )

    # Must fail closed with INTERNAL_RUNTIME_FAILURE and must NOT fallback
    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.engine == "fake-cleanup-fail"
    assert any(f.code == "credential_cleanup_failed" for f in record.detected_failures)
    assert result.generation is None


def test_credential_preparation_failure_fails_closed(tmp_path: Path):
    """Provider preparation failure -> INTERNAL_RUNTIME_FAILURE without engine run (goal.md §7.5)."""
    class BrokenProvider:
        provider_id = "broken"
        def prepare(self, engine_name: str, credentials_dir: Path):
            raise RuntimeError("provider vault unavailable")

    engine = _engine("fake-prep-fail", modes=("valid",), credential_provider=BrokenProvider())
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert any(f.code == "credential_preparation_failed" for f in record.detected_failures)


def test_credential_context_suppresses_secrets_in_dumps_and_repr():
    """Secret fields excluded from model_dump and repr (goal.md §7.3)."""
    context = CredentialContext(
        public_env={"USER_NAME": "test_user"},
        secret_env={"API_KEY": "super_secret_key_value_123"},
        ephemeral_files=(Path("/tmp/ephemeral_file.txt"),),
        exact_redaction_values=(b"super_secret_key_value_123",),
        provider_id="synthetic",
        nonsecret_configuration_fingerprint=Sha256("sha256:" + "0" * 64),
    )

    dumped = context.model_dump(mode="json")
    assert "USER_NAME" in dumped["public_env"]
    assert "secret_env" not in dumped
    assert "ephemeral_files" not in dumped
    assert "exact_redaction_values" not in dumped

    repr_str = repr(context)
    assert "super_secret_key_value_123" not in repr_str
    assert "ephemeral_file.txt" not in repr_str
