"""Trusted output-directory identity conformance (goal.md §7.7, §7.14).

The parent opens ``output/`` before launch and anchors its identity to the
opened inode. After process exit the path is re-checked: a replaced, removed
or symlinked output directory is ``ENGINE_OUTPUT_POLICY_FAILURE`` with the
``output_directory_replaced`` failure code (stage ``output_tree``), and this
check precedes any proposal classification — even when the replaced directory
contains a contract-valid proposal.
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path

import pytest

from vibereview.runtime import (
    AttemptFailureStage,
    AttemptOutcome,
    ConfinementLevel,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    RuntimeResult,
    SubprocessEngine,
    SubprocessExecutionResult,
    TaskAttemptRecord,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.hashing import hash_bytes
from vibereview.runtime.output_policy import (
    open_tracked_output_dir,
    verify_output_directory_identity,
)

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

_VALID_PROPOSAL_BYTES = json.dumps(
    {
        "themes": [
            {
                "local_ref": "theme_1",
                "title": "Thermal management",
                "description": "Generated by deterministic fixture",
                "origin": "generated",
                "parent_ref": None,
            }
        ],
        "claims": [
            {
                "local_ref": "claim_1",
                "theme_ref": "theme_1",
                "candidate_claim": "Preheating changes residual stress.",
                "origin": "generated",
                "origin_refs": [],
            }
        ],
    }
).encode("utf-8")


def _engine(name: str, modes: tuple[str, ...]) -> SubprocessEngine:
    return SubprocessEngine(
        worker_script=WORKER,
        modes=modes,
        proposal_payloads={"valid_proposal.json": _VALID_PROPOSAL_BYTES},
        policy=deterministic_test_policy(),
        name=name,
    )


def _run_claims(
    tmp_path: Path, engines: list[SubprocessEngine]
) -> tuple[ProjectRuntime, RuntimeResult]:
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="output-identity"
    )
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
        engines=engines,
    )
    return runtime, result


def _attempt_dir(runtime: ProjectRuntime, record: TaskAttemptRecord) -> Path:
    return (
        runtime.project_root
        / "work"
        / "tasks"
        / record.task_id
        / "attempts"
        / record.attempt_id
    )


def _execution_report(
    runtime: ProjectRuntime, record: TaskAttemptRecord
) -> SubprocessExecutionResult:
    agent_result = json.loads(
        (runtime.project_root / record.agent_result_path).read_text(encoding="utf-8")
    )
    return SubprocessExecutionResult.model_validate(agent_result["execution_report"])


def test_output_directory_replacement_is_output_policy_failure(tmp_path):
    runtime, result = _run_claims(
        tmp_path, [_engine("replace-output", ("output_directory_replacement",))]
    )
    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert result.generation is None
    assert runtime.store.current_generation() == 0
    assert len(result.attempt_records) == 1

    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert record.accepted_attempt is False
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.validation_errors == [
        "output directory was replaced during execution"
    ]

    # Exactly one detected failure: the st_dev/st_ino identity mismatch.
    assert len(record.detected_failures) == 1
    failure = record.detected_failures[0]
    assert failure.code == "output_directory_replaced"
    assert failure.stage is AttemptFailureStage.OUTPUT_TREE
    assert failure.relative_path == Path("output")
    assert failure.message == "output directory was replaced during execution"

    # The worker process itself succeeded; only the identity check failed.
    report = _execution_report(runtime, record)
    assert report.primary_outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert report.confinement_level is ConfinementLevel.TEST_ONLY
    assert report.exit_code == 0
    assert report.timed_out is False
    assert report.launch_error is None
    assert report.resource_limit_breached is False
    assert report.bundle_modified is False
    assert report.output_policy_violated is True
    assert report.proposal_format_invalid is False
    assert report.detected_failures == record.detected_failures


def test_replaced_directory_proposal_is_never_imported(tmp_path):
    # The worker copies a contract-valid proposal into the *replaced* output
    # directory. The identity check fires first, so that proposal must never
    # be opened, classified or treated as importable.
    runtime, result = _run_claims(
        tmp_path, [_engine("replace-output", ("output_directory_replacement",))]
    )
    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    record = result.attempt_records[0]
    report = _execution_report(runtime, record)

    # No proposal text ever surfaced to the kernel.
    assert record.output_hash is None
    assert not (_attempt_dir(runtime, record) / "proposal.json").exists()
    task_dir = runtime.project_root / "work" / "tasks" / record.task_id
    assert not (task_dir / "accepted" / "proposal.json").exists()

    # Import was skipped entirely: no proposal-file or format classification,
    # in particular no missing-proposal classification.
    assert report.proposal_format_invalid is False
    stages = {failure.stage for failure in record.detected_failures}
    assert AttemptFailureStage.PROPOSAL_FILE not in stages
    assert AttemptFailureStage.FORMAT not in stages
    codes = {failure.code for failure in record.detected_failures}
    assert "proposal_missing" not in codes

    # The inventory recorded nothing under output/: the replaced directory's
    # proposal was never opened or hashed.
    assert not any(
        entry.relative_path.parts[:1] == ("output",) for entry in report.inventory
    )
    payload_hash = hash_bytes(_VALID_PROPOSAL_BYTES)
    assert payload_hash not in {entry.content_hash for entry in report.inventory}
    # The stashed original directory sits outside the writable roots and must
    # not leak into the inventory either.
    assert not any(
        "output.original" in entry.relative_path.parts
        for entry in report.inventory
    )
    assert result.generation is None
    assert runtime.store.current_generation() == 0


def test_output_directory_replacement_precedes_malformed_proposal(tmp_path):
    # After replacement the new output/ contains malformed JSON; the §6.6
    # priority-4 output-policy failure must still win over priority-5 format.
    runtime, result = _run_claims(
        tmp_path,
        [_engine("replace-malformed", ("output_directory_replacement", "malformed_json"))],
    )
    assert result.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert result.generation is None
    assert runtime.store.current_generation() == 0

    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert [failure.code for failure in record.detected_failures] == [
        "output_directory_replaced"
    ]

    report = _execution_report(runtime, record)
    assert report.primary_outcome is AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE
    assert report.output_policy_violated is True
    assert report.exit_code == 0
    # The malformed bytes were never parsed: format classification never ran.
    assert report.proposal_format_invalid is False


def test_output_policy_failure_falls_back_to_fresh_output_directory(tmp_path):
    # ENGINE_OUTPUT_POLICY_FAILURE is fallback-eligible (§6.3); the fallback
    # attempt receives a fresh trusted output directory that passes identity.
    replacing = _engine("replace-output", ("output_directory_replacement",))
    valid = _engine("valid-output", ("valid",))
    runtime, result = _run_claims(tmp_path, [replacing, valid])
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1

    records = result.attempt_records
    assert [record.outcome for record in records] == [
        AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    first, second = records
    assert first.attempt_id == "01-replace-output"
    assert second.attempt_id == "02-valid-output"
    assert [failure.code for failure in first.detected_failures] == [
        "output_directory_replaced"
    ]
    assert second.detected_failures == ()
    assert second.accepted_attempt is True

    # Contrast: a trusted output directory's proposal is inventoried, hashed
    # and imported; the replaced directory's proposal (above) never is.
    report = _execution_report(runtime, second)
    assert report.output_policy_violated is False
    inventory = {entry.relative_path: entry for entry in report.inventory}
    proposal_entry = inventory[Path("output") / "proposal.json"]
    assert proposal_entry.file_type == "regular"
    assert proposal_entry.size_bytes == len(_VALID_PROPOSAL_BYTES)
    assert proposal_entry.content_hash == hash_bytes(_VALID_PROPOSAL_BYTES)


def test_open_tracked_output_dir_records_device_and_inode(tmp_path):
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    descriptor, trusted = open_tracked_output_dir(output_dir)
    try:
        current = os.stat(output_dir)
        assert stat.S_ISDIR(trusted.st_mode)
        assert (trusted.st_dev, trusted.st_ino) == (
            current.st_dev,
            current.st_ino,
        )
    finally:
        os.close(descriptor)


def test_open_tracked_output_dir_refuses_symlink(tmp_path):
    target = tmp_path / "target"
    target.mkdir()
    link = tmp_path / "output"
    link.symlink_to(target, target_is_directory=True)
    with pytest.raises(OSError):
        open_tracked_output_dir(link)


def test_identity_holds_for_untouched_directory(tmp_path):
    # Negative control: an ordinary proposal write changes neither st_dev nor
    # st_ino of the directory, so the identity check must pass.
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    descriptor, trusted = open_tracked_output_dir(output_dir)
    try:
        (output_dir / "proposal.json").write_bytes(_VALID_PROPOSAL_BYTES)
        assert verify_output_directory_identity(output_dir, trusted) is None
    finally:
        os.close(descriptor)


def test_identity_detects_rename_replacement(tmp_path):
    # Mirrors the worker's output_directory_replacement mode.
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    descriptor, trusted = open_tracked_output_dir(output_dir)
    try:
        os.rename(output_dir, tmp_path / "output.original")
        output_dir.mkdir()
        failure = verify_output_directory_identity(output_dir, trusted)
        assert failure is not None
        assert failure.code == "output_directory_replaced"
        assert failure.stage is AttemptFailureStage.OUTPUT_TREE
        assert failure.relative_path == Path("output")
        assert failure.message == "output directory was replaced during execution"
    finally:
        os.close(descriptor)


def test_identity_rejects_symlinked_directory(tmp_path):
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    descriptor, trusted = open_tracked_output_dir(output_dir)
    try:
        aside = tmp_path / "output.original"
        os.rename(output_dir, aside)
        output_dir.symlink_to(aside, target_is_directory=True)
        failure = verify_output_directory_identity(output_dir, trusted)
        assert failure is not None
        assert failure.code == "output_directory_replaced"
        assert failure.stage is AttemptFailureStage.OUTPUT_TREE
        assert failure.message == "output directory is no longer a real directory"
    finally:
        os.close(descriptor)


def test_identity_rejects_removed_directory(tmp_path):
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    descriptor, trusted = open_tracked_output_dir(output_dir)
    try:
        output_dir.rmdir()
        failure = verify_output_directory_identity(output_dir, trusted)
        assert failure is not None
        assert failure.code == "output_directory_replaced"
        assert failure.stage is AttemptFailureStage.OUTPUT_TREE
        assert failure.message == "output directory was removed during execution"
    finally:
        os.close(descriptor)
