"""Tests for trusted launcher and applied resource limits (goal.md §6)."""

from __future__ import annotations

import json
import os
import signal
import subprocess
import sys
from pathlib import Path

import pytest

from vibereview.runtime import (
    AttemptOutcome,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    ResourceLimitCode,
    SubprocessAgentResult,
    SubprocessEngine,
    SubprocessPolicy,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.applied_limits import AppliedResourceLimit
from vibereview.runtime.launcher_policy import LauncherPolicy
from vibereview.runtime.trusted_launcher import apply_limits

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

VALID_PROPOSAL = {
    "themes": [
        {
            "local_ref": "theme_1",
            "title": "Thermal management",
            "description": "Generated by deterministic fixture",
            "origin": "generated",
            "parent_ref": None,
        }
    ],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "theme_1",
            "candidate_claim": "Preheating changes residual stress.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}


def _engine(
    name: str,
    *,
    modes: tuple[str, ...] = ("valid",),
    policy: SubprocessPolicy | None = None,
    launcher_policy: LauncherPolicy | None = None,
    worker_config: dict | None = None,
) -> SubprocessEngine:
    return SubprocessEngine(
        name=name,
        worker_script=WORKER,
        modes=modes,
        policy=policy,
        launcher_policy=launcher_policy,
        worker_config=worker_config,
        proposal_payloads={
            "valid_proposal.json": json.dumps(VALID_PROPOSAL).encode("utf-8")
        },
    )


def _init_runtime(tmp_path: Path) -> ProjectRuntime:
    project_dir = tmp_path / "project"
    return ProjectRuntime.create(project_dir, project_name="launcher-test")


def _run_task(runtime: ProjectRuntime, engine: SubprocessEngine):
    return runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="Additive manufacturing", existing_theme_ids=[]),
        engines=[engine],
    )


def test_trusted_launcher_applies_nofile_and_probe_reads_it(tmp_path: Path):
    """Probe inside child reads expected RLIMIT_NOFILE (goal.md §6.6)."""
    policy = deterministic_test_policy().model_copy(
        update={"max_open_files": 256}
    )
    engine = _engine("fake-nofile", modes=("rlimit_nofile_probe", "valid"), policy=policy)
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    record = result.attempt_records[0]
    agent_result_path = runtime.project_root / record.agent_result_path
    agent_result = SubprocessAgentResult.model_validate_json(
        agent_result_path.read_text(encoding="utf-8")
    )
    stdout = agent_result.stdout
    assert "RLIMIT_NOFILE=" in stdout
    soft_str = stdout.split("RLIMIT_NOFILE=")[1].split(",")[0].strip()
    assert int(soft_str) == 256

    # Verify applied_limits report in execution_report
    report = agent_result.execution_report
    applied_codes = {item.code: item for item in report.applied_limits}
    assert ResourceLimitCode.MAX_OPEN_FILES in applied_codes
    nofile_record = applied_codes[ResourceLimitCode.MAX_OPEN_FILES]
    assert nofile_record.requested_value == 256
    assert nofile_record.applied_soft_value == 256
    assert nofile_record.supported is True
    assert nofile_record.authoritative is True


def test_trusted_launcher_preserves_explicit_inheritable_executable_fd(
    tmp_path: Path,
) -> None:
    launcher_dir = tmp_path / "launcher"
    launcher_dir.mkdir()
    policy_path = launcher_dir / "launcher_policy.json"
    report_path = launcher_dir / "applied_limits.json"
    policy_path.write_text("{}\n", encoding="utf-8")
    executable_fd = os.open("/bin/true", os.O_RDONLY)
    try:
        os.set_inheritable(executable_fd, True)
        completed = subprocess.run(
            [
                sys.executable,
                str(Path(__file__).resolve().parents[2] / "src/vibereview/runtime/trusted_launcher.py"),
                "--policy", str(policy_path),
                "--report", str(report_path),
                "--", f"/proc/self/fd/{executable_fd}",
            ],
            pass_fds=(executable_fd,),
            capture_output=True,
            text=True,
            timeout=5,
        )
    finally:
        os.close(executable_fd)
    assert completed.returncode == 0, completed.stderr
    assert report_path.is_file()


def test_cpu_spin_reaches_limit_and_attributable_failure(tmp_path: Path):
    """CPU spin reaches configured limit -> attributable resource limit failure (goal.md §6.6)."""
    policy = deterministic_test_policy().model_copy(
        update={"max_cpu_seconds": 1, "timeout_seconds": 15.0}
    )
    engine = _engine("fake-cpu-spin", modes=("cpu_spin",), policy=policy)
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    record = result.attempt_records[0]
    assert any(
        f.code == ResourceLimitCode.MAX_CPU_TIME.value for f in record.detected_failures
    )


def test_rlimit_fsize_exceeded_triggers_attributable_failure(tmp_path: Path):
    """File write exceeds RLIMIT_FSIZE -> SIGXFSZ and bounded failure (goal.md §6.6)."""
    engine = _engine(
        "fake-fsize",
        modes=("fsize_write",),
        launcher_policy=LauncherPolicy(max_writable_single_file_bytes=1024 * 1024),
    )
    runtime = _init_runtime(tmp_path)
    result = _run_task(runtime, engine)

    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    record = result.attempt_records[0]
    assert any(
        f.code == ResourceLimitCode.MAX_WRITABLE_SINGLE_FILE_BYTES.value
        for f in record.detected_failures
    )


def test_launcher_policy_in_forbidden_directory_is_rejected(tmp_path: Path):
    """Launcher rejects policy from bundle, output, scratch with 125 (goal.md §6.2)."""
    launcher_py = Path(__file__).resolve().parent.parent.parent / "src" / "vibereview" / "runtime" / "trusted_launcher.py"

    # Create dummy policy in scratch/
    scratch_dir = tmp_path / "scratch"
    scratch_dir.mkdir()
    bad_policy = scratch_dir / "launcher_policy.json"
    bad_policy.write_text("{}", encoding="utf-8")
    report = tmp_path / "report.json"

    cmd = [
        sys.executable,
        str(launcher_py),
        "--policy",
        str(bad_policy),
        "--report",
        str(report),
        "--",
        sys.executable,
        "-c",
        "print('hello')",
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    assert res.returncode == 125
    assert "policy" in res.stderr.lower()


def test_launcher_exit_125_fails_closed_as_internal_runtime_failure(tmp_path: Path):
    """Launcher failure before launch maps to INTERNAL_RUNTIME_FAILURE without fallback (goal.md §6.5)."""
    class Exit125Engine(SubprocessEngine):
        def _run(self, session, credentials, started):
            launcher = session.launcher_dir / "trusted_launcher.py"
            launcher.chmod(0o700)
            launcher.write_text(
                "import sys; sys.exit(125)\n", encoding="utf-8"
            )
            return super()._run(session, credentials, started)

    runtime_bad = ProjectRuntime.create(tmp_path / "project_bad", project_name="bad-launcher")
    engine_bad = Exit125Engine(
        name="bad-launcher-engine",
        worker_script=WORKER,
        modes=("valid",),
        proposal_payloads={
            "valid_proposal.json": json.dumps(VALID_PROPOSAL).encode("utf-8")
        },
    )
    result = _run_task(runtime_bad, engine_bad)

    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    record = result.attempt_records[0]
    assert any(f.code == "launcher_setrlimit_failed" for f in record.detected_failures)


def test_applied_limits_model_and_distinction():
    """Verify RLIMIT_NPROC and RLIMIT_AS are defense-in-depth/non-authoritative (goal.md §6.4)."""
    policy_dict = {
        "max_open_files": 512,
        "max_processes": 32,
        "max_address_space_bytes": 1024 * 1024 * 1024,
    }
    records = apply_limits(policy_dict)
    models = [AppliedResourceLimit.model_validate(r) for r in records]

    by_code = {m.code: m for m in models}
    if ResourceLimitCode.MAX_OPEN_FILES in by_code:
        assert by_code[ResourceLimitCode.MAX_OPEN_FILES].authoritative is True
    if ResourceLimitCode.MAX_PROCESS_COUNT in by_code:
        assert by_code[ResourceLimitCode.MAX_PROCESS_COUNT].authoritative is False
    if ResourceLimitCode.MAX_ADDRESS_SPACE in by_code:
        assert by_code[ResourceLimitCode.MAX_ADDRESS_SPACE].authoritative is False
