"""Milestone-A privacy: engine-visible artifacts never carry live paths.

Every file an engine can reach — the immutable ``bundle/`` template and each
per-attempt ``attempts/*/workspace/`` copy — is scanned byte-by-byte for the
project root, the canonical state/generation directories, the original
resource source paths, the user home, and any reference to the task's
``private/`` trust-anchor directory. Resource sources live outside the
project root in a simulated user home so the forbidden strings are real.
"""

from __future__ import annotations

import json
import os
import re
from collections.abc import Iterator
from pathlib import Path, PurePosixPath

from vibereview.runtime import (
    AgentTask,
    AssessClaimInvocation,
    AttemptOutcome,
    CandidateClaimProposal,
    ClaimAssessmentProposal,
    DiscoveryProposalBundle,
    MockEngine,
    MockResponse,
    ParseDeepResearchInvocation,
    ProjectRuntime,
    RepositorySnapshot,
    TaskType,
    ThemeProposal,
)

TOPIC = "residual stress"

# Tokens naming the task's private/ directory or the files it holds. The bare
# directory name is asserted too: no engine-visible byte may reference it.
PRIVATE_REFERENCES = ("private", "task_provenance", "resource_sources", "invocation.json")


def _discovery_proposal() -> DiscoveryProposalBundle:
    return DiscoveryProposalBundle(
        themes=[
            ThemeProposal(
                local_ref="theme_1",
                title="Thermal management",
                description="Generated by deterministic fixture",
                origin="generated",
            )
        ],
        claims=[
            CandidateClaimProposal(
                local_ref="claim_1",
                theme_ref="theme_1",
                candidate_claim="Preheating changes residual stress.",
                origin="generated",
                origin_refs=[],
            )
        ],
    )


def _retain_proposal() -> ClaimAssessmentProposal:
    return ClaimAssessmentProposal(
        claim_ref="C0001",
        aggregate_strength="high",
        evidence_sufficiency="sufficient",
        decision="RETAIN",
        rejection_basis=None,
        support_summary="One direct publication-level result.",
        contradiction_summary="None in the supplied corpus.",
        qualification_summary="Applies to the tested process window.",
        reason="Evidence is sufficient for retention.",
    )


def _snapshot_without_downstream_claim_objects(bundle_factory) -> RepositorySnapshot:
    bundle = bundle_factory()
    for name in (
        "claim_assessments",
        "final_claim_validations",
        "claim_packets",
        "proposition_records",
        "semantic_audits",
        "rendered_sentences",
        "rendered_sentence_audits",
    ):
        bundle[name] = []
    return RepositorySnapshot.model_validate(bundle)


def _run_deep_research(tmp_path: Path):
    """End-to-end PARSE_DEEP_RESEARCH with sources outside the project root.

    The documents live in a simulated user home; the runtime is configured
    with that home as an allowed source root. The primary engine fails so a
    fallback attempt runs, leaving two per-attempt workspaces to scan.
    """

    home = tmp_path / "home" / "user"
    documents_dir = home / "documents"
    documents_dir.mkdir(parents=True)
    alpha = documents_dir / "alpha.md"
    beta = documents_dir / "beta notes.md"
    alpha.write_text(
        "# Alpha survey\n\nResidual stress findings α β γ.\n", encoding="utf-8"
    )
    beta.write_text(
        "# Beta notes\n\nPreheating reduced distortion.\n", encoding="utf-8"
    )
    runtime = ProjectRuntime.create(
        tmp_path / "project",
        project_name="privacy",
        allowed_source_roots=(home,),
    )
    captured: list[tuple[str, AgentTask]] = []
    primary = MockEngine(
        [MockResponse(execution_error="primary unavailable")],
        name="primary",
        on_execute=lambda task, _call: captured.append(("primary", task)),
    )
    fallback = MockEngine(
        [MockResponse(proposal=_discovery_proposal().model_dump(mode="json"))],
        name="fallback",
        on_execute=lambda task, _call: captured.append(("fallback", task)),
    )
    result = runtime.run(
        TaskType.PARSE_DEEP_RESEARCH,
        ParseDeepResearchInvocation(topic=TOPIC, document_paths=[alpha, beta]),
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_EXECUTION_FAILURE,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    return runtime, result, task_dir, (alpha, beta), home, captured


def _live_path_needles(*paths: Path) -> list[str]:
    needles: set[str] = set()
    for path in paths:
        for candidate in (Path(path), path.resolve(), Path(os.path.realpath(path))):
            needles.add(str(candidate))
    return sorted(needles)


def _engine_visible_files(task_dir: Path) -> list[Path]:
    workspaces = sorted((task_dir / "attempts").glob("*/workspace"))
    assert workspaces, "expected at least one attempt workspace to scan"
    files = [
        path
        for root in (task_dir / "bundle", *workspaces)
        for path in sorted(root.rglob("*"))
        if path.is_file()
    ]
    assert files, "the privacy scan must not be vacuous"
    return files


def _assert_files_avoid(files: list[Path], needles: list[str]) -> None:
    for path in files:
        content = path.read_bytes()
        for needle in needles:
            assert needle.encode("utf-8") not in content, (
                f"forbidden reference {needle!r} leaked into engine-visible {path}"
            )


def _iter_strings(payload: object) -> Iterator[str]:
    if isinstance(payload, str):
        yield payload
    elif isinstance(payload, dict):
        for value in payload.values():
            yield from _iter_strings(value)
    elif isinstance(payload, list):
        for item in payload:
            yield from _iter_strings(item)


def _iter_keys(payload: object) -> Iterator[str]:
    if isinstance(payload, dict):
        for key, value in payload.items():
            yield key
            yield from _iter_keys(value)
    elif isinstance(payload, list):
        for item in payload:
            yield from _iter_keys(item)


def _deep_research_needles(
    runtime: ProjectRuntime,
    result,
    documents: tuple[Path, ...],
    home: Path,
    tmp_path: Path,
) -> list[str]:
    return [
        *_live_path_needles(
            runtime.project_root,
            runtime.store.state_dir,
            runtime.store.generations_dir,
            runtime.store.generation_path(0),
            runtime.store.generation_path(result.generation or 0),
            home,
            documents[0].parent,
            *documents,
            tmp_path,
            Path.home(),
        ),
        *PRIVATE_REFERENCES,
    ]


def test_engine_visible_files_never_leak_live_paths(tmp_path):
    runtime, result, task_dir, documents, home, _captured = _run_deep_research(tmp_path)
    workspaces = sorted((task_dir / "attempts").glob("*/workspace"))
    # Both the failed primary attempt and the accepted fallback attempt left a
    # workspace; every tree an engine touched is scanned, plus the template.
    assert [workspace.parent.name for workspace in workspaces] == [
        "01-primary",
        "02-fallback",
    ]
    files = _engine_visible_files(task_dir)
    needles = _deep_research_needles(runtime, result, documents, home, tmp_path)
    # Sanity: the forbidden locations genuinely existed on disk during the run,
    # so a leak would have had something to leak.
    assert runtime.store.generations_dir.is_dir()
    assert all(document.is_file() for document in documents)
    _assert_files_avoid(files, needles)


def test_private_trust_anchor_is_the_only_place_source_paths_live(tmp_path):
    runtime, result, task_dir, documents, home, _captured = _run_deep_research(tmp_path)
    private_dir = task_dir / "private"
    provenance = json.loads(
        (private_dir / "task_provenance.json").read_text(encoding="utf-8")
    )
    # The private trust anchor records the authoritative hashes and the
    # resolved source path of every snapshotted resource.
    recorded = {
        entry["resource_id"]: entry["source_path"] for entry in provenance["resources"]
    }
    assert recorded == {
        "RES0001": str(documents[0].resolve()),
        "RES0002": str(documents[1].resolve()),
    }
    assert provenance["expected_bundle_manifest_hash"].startswith("sha256:")
    immutable = provenance["expected_immutable_files"]
    assert immutable["input/resources/RES0001/content.md"].startswith("sha256:")
    sources_text = (private_dir / "resource_sources.json").read_text(encoding="utf-8")
    invocation_text = (private_dir / "invocation.json").read_text(encoding="utf-8")
    for document in documents:
        assert str(document) in sources_text
        assert str(document) in invocation_text
    # The very same source paths are absent from every engine-visible file,
    # which also proves the scanner above is not vacuous.
    files = _engine_visible_files(task_dir)
    needles = _deep_research_needles(runtime, result, documents, home, tmp_path)
    _assert_files_avoid(files, needles)


def test_engine_input_and_manifest_reference_resources_by_id_only(tmp_path):
    _runtime, _result, task_dir, _documents, _home, _captured = _run_deep_research(
        tmp_path
    )
    input_json = json.loads(
        (task_dir / "bundle" / "input" / "input.json").read_text(encoding="utf-8")
    )
    # The engine input names resources exclusively through task-local RES ids.
    assert input_json == {
        "topic": TOPIC,
        "document_resource_ids": ["RES0001", "RES0002"],
    }
    for value in _iter_strings(input_json):
        assert value == TOPIC or re.fullmatch(r"RES[0-9]{4,}", value), value

    manifest = json.loads(
        (task_dir / "bundle" / "bundle_manifest.json").read_text(encoding="utf-8")
    )
    # The engine-readable manifest carries no source paths at all.
    assert "source_path" not in set(_iter_keys(manifest))
    assert [entry["resource_id"] for entry in manifest["resources"]] == [
        "RES0001",
        "RES0002",
    ]
    for entry in manifest["resources"]:
        relative = PurePosixPath(entry["path"])
        assert not relative.is_absolute()
        assert ".." not in relative.parts
        assert entry["path"] == f"input/resources/{entry['resource_id']}/content.md"
        assert (task_dir / "bundle" / entry["path"]).is_file()
    for entry in manifest["dependencies"]:
        assert not PurePosixPath(entry["path"]).is_absolute()

    # The attempt workspace received the same sanitized input bytes.
    bundle_input = (task_dir / "bundle" / "input" / "input.json").read_bytes()
    for workspace in sorted((task_dir / "attempts").glob("*/workspace")):
        assert (workspace / "input" / "input.json").read_bytes() == bundle_input


def test_agent_task_exposes_only_the_attempt_workspace(tmp_path):
    runtime, result, task_dir, _documents, _home, captured = _run_deep_research(
        tmp_path
    )
    assert [engine for engine, _task in captured] == ["primary", "fallback"]
    private_dir = task_dir / "private"
    master_bundle = task_dir / "bundle"
    state_dir = runtime.store.state_dir
    for _engine, task in captured:
        assert task.task_id == task_dir.name
        assert task.attempt_dir.parent == task_dir / "attempts"
        assert task.workspace_dir == task.attempt_dir / "workspace"
        assert task.instructions_path == task.workspace_dir / "instructions.md"
        assert task.input_dir == task.workspace_dir / "input"
        for exposed in (
            task.workspace_dir,
            task.instructions_path,
            task.input_dir,
            task.attempt_dir,
        ):
            # Nothing the engine is handed points at the private trust anchor,
            # the immutable master bundle, or live canonical state.
            assert private_dir not in (exposed, *exposed.parents)
            assert master_bundle not in (exposed, *exposed.parents)
            assert state_dir not in (exposed, *exposed.parents)
        assert not (task.workspace_dir / "private").exists()


def test_structured_dependency_files_contain_canonical_objects_only(
    tmp_path, bundle_factory
):
    snapshot = _snapshot_without_downstream_claim_objects(bundle_factory)
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="privacy-deps", initial_snapshot=snapshot
    )
    engine = MockEngine(
        [MockResponse(proposal=_retain_proposal().model_dump(mode="json"))]
    )
    result = runtime.run(
        TaskType.ASSESS_CLAIM,
        AssessClaimInvocation(
            claim_id="C0001", claim_paper_evidence_ids=["CPE-C0001-P0001"]
        ),
        engines=[engine],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    task_dir = runtime.project_root / "work" / "tasks" / result.task_id

    dependency_dir = task_dir / "bundle" / "input" / "dependencies"
    dependency_files = {path.name: path for path in dependency_dir.glob("*.json")}
    dependency_keys = (
        "CandidateClaim:C0001",
        "ClaimPaperEvidence:CPE-C0001-P0001",
        "Paper:P0001",
        "EvidenceRecord:E0001",
        "RetrievedSpan:R0001",
        "RetrievalDisposition:R0001",
        "RetrievalQuery:Q-C0001-SUP-01",
    )
    canonical_index = snapshot.object_index()
    expected_dependencies = {
        f"{key.replace(':', '__')}.json": canonical_index[key]
        for key in dependency_keys
    }
    assert set(dependency_files) == set(expected_dependencies)
    for name, canonical in expected_dependencies.items():
        payload = json.loads(
            dependency_files[name].read_text(encoding="utf-8")
        )
        assert payload == canonical.model_dump(mode="json")
        assert set(payload) == set(type(canonical).model_fields)
    # Canonical data only: no absolute path of any kind inside dependencies.
    for name, path in dependency_files.items():
        payload = json.loads(path.read_text(encoding="utf-8"))
        for value in _iter_strings(payload):
            assert not value.startswith("/"), (name, value)
            assert not re.match(r"^[A-Za-z]:[\\/]", value), (name, value)

    # The whole engine-visible surface of a structured task is path-free too.
    files = _engine_visible_files(task_dir)
    needles = [
        *_live_path_needles(
            runtime.project_root,
            runtime.store.state_dir,
            runtime.store.generations_dir,
            tmp_path,
            Path.home(),
        ),
        *PRIVATE_REFERENCES,
    ]
    _assert_files_avoid(files, needles)
