"""Milestone-A attempt isolation and bundle-integrity failure taxonomy."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vibereview.runtime import (
    AttemptOutcome,
    BundleIntegrityError,
    CandidateClaimProposal,
    DiscoveryProposalBundle,
    MockEngine,
    MockResponse,
    ParseDeepResearchInvocation,
    ProjectRuntime,
    TaskType,
    ThemeProposal,
)
from vibereview.runtime.hashing import hash_file
from vibereview.runtime.tasks import TaskWorkspace


def _proposal() -> DiscoveryProposalBundle:
    return DiscoveryProposalBundle(
        themes=[
            ThemeProposal(
                local_ref="theme_1",
                title="Thermal management",
                description="Generated by deterministic fixture",
                origin="generated",
            )
        ],
        claims=[
            CandidateClaimProposal(
                local_ref="claim_1",
                theme_ref="theme_1",
                candidate_claim="Preheating changes residual stress.",
                origin="generated",
                origin_refs=[],
            )
        ],
    )


def _runtime_with_document(tmp_path) -> tuple[ProjectRuntime, Path]:
    project = tmp_path / "project"
    documents = project / "input" / "deep_research"
    documents.mkdir(parents=True)
    document = documents / "survey.md"
    document.write_text(
        "# Deep research\n\nResidual stress findings.\n", encoding="utf-8"
    )
    runtime = ProjectRuntime.create(project, project_name="isolation")
    return runtime, document


def _run(runtime: ProjectRuntime, document: Path, *engines: MockEngine):
    return runtime.run(
        TaskType.PARSE_DEEP_RESEARCH,
        ParseDeepResearchInvocation(topic="residual stress", document_paths=[document]),
        engines=list(engines),
    )


def _tree_bytes(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _engine(name: str, on_execute=None) -> MockEngine:
    return MockEngine(
        [MockResponse(proposal=_proposal().model_dump(mode="json"))],
        name=name,
        on_execute=on_execute,
    )


TAMPER_TARGETS = [
    "instructions.md",
    "bundle_manifest.json",
    "contracts/input.schema.json",
    "contracts/proposal.schema.json",
    "input/input.json",
    "input/resources/RES0001/content.md",
]


@pytest.mark.parametrize("target", TAMPER_TARGETS)
def test_tampering_primary_fails_integrity_and_fallback_gets_clean_workspace(
    tmp_path, target
):
    runtime, document = _runtime_with_document(tmp_path)

    def tamper(task, call_number):
        path = task.workspace_dir / target
        path.chmod(0o644)
        path.write_text("tampered by primary engine\n", encoding="utf-8")

    observed: dict[str, object] = {}

    def inspect(task, call_number):
        observed["workspace_dir"] = task.workspace_dir
        observed["attempt_dir"] = task.attempt_dir
        observed["has_private"] = (task.workspace_dir / "private").exists()
        observed["instructions"] = task.instructions_path.read_text(encoding="utf-8")

    primary = _engine("primary", on_execute=tamper)
    fallback = _engine("fallback", on_execute=inspect)
    result = _run(runtime, document, primary, fallback)

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    assert [record.engine for record in result.attempt_records] == [
        "primary",
        "fallback",
    ]
    assert primary.calls == 1
    assert fallback.calls == 1

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    master = task_dir / "bundle"

    # The engine only ever saw a per-attempt workspace, never private/ or the
    # master bundle, and the fallback received an untampered fresh copy.
    workspace_dir = observed["workspace_dir"]
    assert workspace_dir == task_dir / "attempts" / "02-fallback" / "workspace"
    assert observed["attempt_dir"] == task_dir / "attempts" / "02-fallback"
    assert not observed["has_private"]
    assert "tampered by primary engine" not in observed["instructions"]

    # The primary's tampering is confined to its own attempt workspace.
    tampered = task_dir / "attempts" / "01-primary" / "workspace" / target
    assert tampered.read_text(encoding="utf-8") == "tampered by primary engine\n"
    with pytest.raises(BundleIntegrityError):
        runtime.tasks.verify_workspace(
            task_dir, task_dir / "attempts" / "01-primary" / "workspace"
        )

    # The master bundle template stays byte-identical and read-only, and the
    # fallback workspace matched it exactly.
    assert _tree_bytes(workspace_dir) == _tree_bytes(master)
    runtime.tasks.verify_bundle(task_dir)
    for path in master.rglob("*"):
        if path.is_file():
            assert not (path.stat().st_mode & 0o222)


def test_tampering_resource_and_manifest_together_still_fails(tmp_path):
    runtime, document = _runtime_with_document(tmp_path)

    def tamper(task, call_number):
        resource = (
            task.workspace_dir / "input" / "resources" / "RES0001" / "content.md"
        )
        resource.chmod(0o644)
        resource.write_text("forged content\n", encoding="utf-8")
        manifest_path = task.workspace_dir / "bundle_manifest.json"
        manifest_path.chmod(0o644)
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        # The engine rewrites the manifest so it stays "consistent" with the
        # forged resource; the private trust anchor still convicts it.
        for entry in manifest["resources"]:
            entry["sha256"] = hash_file(resource)
            entry["size_bytes"] = resource.stat().st_size
        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
            encoding="utf-8",
        )

    primary = _engine("primary", on_execute=tamper)
    fallback = _engine("fallback")
    result = _run(runtime, document, primary, fallback)

    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    runtime.tasks.verify_bundle(task_dir)


def test_pre_execution_bundle_corruption_is_internal_failure_without_engines(
    tmp_path, monkeypatch
):
    runtime, document = _runtime_with_document(tmp_path)
    original_create = runtime.tasks.create

    def corrupting_create(**kwargs):
        task_dir, manifest, provenance = original_create(**kwargs)
        target = task_dir / "bundle" / "instructions.md"
        target.chmod(0o644)
        target.write_text("corrupted after construction\n", encoding="utf-8")
        return task_dir, manifest, provenance

    monkeypatch.setattr(runtime.tasks, "create", corrupting_create)
    primary = _engine("primary")
    fallback = _engine("fallback")
    result = _run(runtime, document, primary, fallback)

    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    assert result.attempt_records == []
    assert primary.calls == 0
    assert fallback.calls == 0


def test_verify_bundle_detects_missing_extra_and_changed_files(tmp_path):
    runtime, document = _runtime_with_document(tmp_path)
    engine = _engine("mock")
    result = _run(runtime, document, engine)
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    bundle = task_dir / "bundle"

    runtime.tasks.verify_bundle(task_dir)

    changed = bundle / "contracts" / "proposal.schema.json"
    original_bytes = changed.read_bytes()
    changed.chmod(0o644)
    changed.write_text("changed\n", encoding="utf-8")
    with pytest.raises(BundleIntegrityError, match="changed"):
        runtime.tasks.verify_bundle(task_dir)
    changed.write_bytes(original_bytes)
    changed.chmod(0o444)

    extra = bundle / "input" / "resources" / "smuggled.md"
    extra.write_text("smuggled\n", encoding="utf-8")
    with pytest.raises(BundleIntegrityError, match="extra"):
        runtime.tasks.verify_bundle(task_dir)
    extra.unlink()

    target = bundle / "contracts" / "input.schema.json"
    saved = target.read_bytes()
    target.unlink()
    with pytest.raises(BundleIntegrityError, match="missing"):
        runtime.tasks.verify_bundle(task_dir)
    target.write_bytes(saved)
    target.chmod(0o444)
    runtime.tasks.verify_bundle(task_dir)
