"""Milestone-A trust-anchor integrity: private/task_provenance.json convicts forgery.

The engine-readable ``bundle/bundle_manifest.json`` is non-authoritative
(goal.md A5/A9): even when an engine rewrites both an immutable file and the
manifest entry describing it, post-execution verification against the private
expected hashes must still reject the attempt with
``ENGINE_WORKSPACE_INTEGRITY_FAILURE``. Corruption detected before any engine
runs is an ``INTERNAL_RUNTIME_FAILURE`` and never triggers fallback.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vibereview.models import ThemeRecord
from vibereview.runtime import (
    AttemptOutcome,
    BundleIntegrityError,
    CandidateClaimProposal,
    DiscoveryProposalBundle,
    GenerateCandidateClaimsInvocation,
    MockEngine,
    MockResponse,
    ParseDeepResearchInvocation,
    ProjectRuntime,
    RepositorySnapshot,
    TaskType,
    ThemeProposal,
)
from vibereview.runtime.hashing import hash_file
from vibereview.runtime.tasks import TaskWorkspace


def _proposal() -> DiscoveryProposalBundle:
    return DiscoveryProposalBundle(
        themes=[
            ThemeProposal(
                local_ref="theme_1",
                title="Thermal management",
                description="Generated by deterministic fixture",
                origin="generated",
            )
        ],
        claims=[
            CandidateClaimProposal(
                local_ref="claim_1",
                theme_ref="theme_1",
                candidate_claim="Preheating changes residual stress.",
                origin="generated",
                origin_refs=[],
            )
        ],
    )


def _runtime_with_document(tmp_path) -> tuple[ProjectRuntime, Path]:
    project = tmp_path / "project"
    documents = project / "input" / "deep_research"
    documents.mkdir(parents=True)
    document = documents / "survey.md"
    document.write_text(
        "# Deep research\n\nResidual stress findings.\n", encoding="utf-8"
    )
    runtime = ProjectRuntime.create(project, project_name="integrity")
    return runtime, document


def _run(runtime: ProjectRuntime, document: Path, *engines: MockEngine):
    return runtime.run(
        TaskType.PARSE_DEEP_RESEARCH,
        ParseDeepResearchInvocation(topic="residual stress", document_paths=[document]),
        engines=list(engines),
    )


def _engine(name: str, on_execute=None) -> MockEngine:
    return MockEngine(
        [MockResponse(proposal=_proposal().model_dump(mode="json"))],
        name=name,
        on_execute=on_execute,
    )


def _workspace(runtime: ProjectRuntime, task_id: str, attempt_id: str) -> Path:
    return (
        runtime.project_root
        / "work"
        / "tasks"
        / task_id
        / "attempts"
        / attempt_id
        / "workspace"
    )


def _manifest_entries(manifest: dict) -> list[dict]:
    return [
        manifest["instructions"],
        manifest["schemas"]["input"],
        manifest["schemas"]["proposal"],
        manifest["engine_input"],
        *manifest["dependencies"],
        *manifest["resources"],
    ]


def _manifest_self_consistency_errors(workspace: Path) -> list[str]:
    """Errors from checking files against the engine-readable manifest only.

    A successful double forgery leaves this list empty: the manifest alone
    cannot convict the workspace, which is exactly why A5 keeps authoritative
    expected hashes under private/task_provenance.json.
    """

    manifest = json.loads(
        (workspace / "bundle_manifest.json").read_text(encoding="utf-8")
    )
    errors: list[str] = []
    for entry in _manifest_entries(manifest):
        path = workspace / entry["path"]
        if not path.is_file():
            errors.append(f"missing {entry['path']}")
            continue
        if hash_file(path) != entry["sha256"]:
            errors.append(f"hash mismatch {entry['path']}")
        if "size_bytes" in entry and path.stat().st_size != entry["size_bytes"]:
            errors.append(f"size mismatch {entry['path']}")
    return errors


def _forge_file_and_manifest(task, relative_path: str, forged_text: str) -> None:
    """Rewrite an immutable workspace file AND its manifest entry (A5 attack)."""

    workspace = task.workspace_dir
    target = workspace / relative_path
    target.chmod(0o644)
    target.write_text(forged_text, encoding="utf-8")
    manifest_path = workspace / "bundle_manifest.json"
    manifest_path.chmod(0o644)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    matched = 0
    for entry in _manifest_entries(manifest):
        if entry["path"] == relative_path:
            entry["sha256"] = hash_file(target)
            if "size_bytes" in entry:
                entry["size_bytes"] = target.stat().st_size
            matched += 1
    assert matched == 1, f"no manifest entry for {relative_path}"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )


def test_double_forgery_of_resource_and_manifest_is_convicted_by_private_anchor(
    tmp_path,
):
    runtime, document = _runtime_with_document(tmp_path)
    target = "input/resources/RES0001/content.md"
    original: dict[str, str] = {}

    def forge(task, call_number):
        # Capture the pristine state the private trust anchor recorded.
        original["resource_hash"] = hash_file(task.workspace_dir / target)
        original["manifest_hash"] = hash_file(
            task.workspace_dir / "bundle_manifest.json"
        )
        _forge_file_and_manifest(task, target, "# forged resource\n")

    forger = _engine("forger", on_execute=forge)
    result = _run(runtime, document, forger)

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    ]
    assert forger.calls == 1
    assert result.generation is None
    assert runtime.store.current_generation() == 0

    record = result.attempt_records[0]
    assert not record.accepted_attempt
    errors = "\n".join(record.validation_errors)
    assert "changed" in errors
    assert target in errors
    assert "bundle_manifest.json" in errors

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    workspace = _workspace(runtime, result.task_id, "01-forger")

    # The forged workspace is self-consistent: verifying the resource against
    # the engine-readable manifest alone would accept the forgery.
    assert _manifest_self_consistency_errors(workspace) == []
    assert hash_file(workspace / target) != original["resource_hash"]
    assert hash_file(workspace / "bundle_manifest.json") != original["manifest_hash"]

    # The private trust anchor still holds the pristine expected hashes and
    # convicts the attempt on its own.
    provenance = TaskWorkspace.load_provenance(task_dir)
    assert provenance.expected_immutable_files[target] == original["resource_hash"]
    assert provenance.expected_bundle_manifest_hash == original["manifest_hash"]
    with pytest.raises(BundleIntegrityError):
        runtime.tasks.verify_workspace(task_dir, workspace)

    # Nothing was canonicalized and the master bundle template is untouched.
    assert not (task_dir / "accepted" / "proposal.json").exists()
    runtime.tasks.verify_bundle(task_dir)


DOUBLE_FORGERY_TARGETS = [
    "instructions.md",
    "input/input.json",
    "contracts/input.schema.json",
    "contracts/proposal.schema.json",
]


@pytest.mark.parametrize("target", DOUBLE_FORGERY_TARGETS)
def test_double_forgery_of_core_bundle_file_is_detected_post_execution(
    tmp_path, target
):
    runtime, document = _runtime_with_document(tmp_path)

    def forge(task, call_number):
        _forge_file_and_manifest(task, target, f"forged {target}\n")

    forger = _engine("forger", on_execute=forge)
    result = _run(runtime, document, forger)

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    ]
    errors = "\n".join(result.attempt_records[0].validation_errors)
    assert target in errors
    assert "bundle_manifest.json" in errors

    workspace = _workspace(runtime, result.task_id, "01-forger")
    assert _manifest_self_consistency_errors(workspace) == []
    with pytest.raises(BundleIntegrityError):
        runtime.tasks.verify_workspace(
            runtime.project_root / "work" / "tasks" / result.task_id, workspace
        )
    runtime.tasks.verify_bundle(runtime.project_root / "work" / "tasks" / result.task_id)


def test_double_forgery_of_structured_dependency_is_detected_post_execution(tmp_path):
    initial = RepositorySnapshot(
        themes=(
            ThemeRecord(
                theme_id="T0001",
                title="Thermal management",
                description="seeded structured dependency",
                origin="human",
                parent_theme_id=None,
            ),
        ),
    )
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="integrity", initial_snapshot=initial
    )
    target = "input/dependencies/ThemeRecord__T0001.json"

    def forge(task, call_number):
        _forge_file_and_manifest(task, target, '{"forged": "dependency"}\n')

    forger = _engine("forger", on_execute=forge)
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=["T0001"]),
        engines=[forger],
    )

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    ]
    errors = "\n".join(result.attempt_records[0].validation_errors)
    assert target in errors
    assert "bundle_manifest.json" in errors

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    workspace = _workspace(runtime, result.task_id, "01-forger")
    assert _manifest_self_consistency_errors(workspace) == []
    provenance = TaskWorkspace.load_provenance(task_dir)
    assert target in provenance.expected_immutable_files
    with pytest.raises(BundleIntegrityError):
        runtime.tasks.verify_workspace(task_dir, workspace)
    runtime.tasks.verify_bundle(task_dir)


def test_deleted_immutable_file_is_detected_post_execution(tmp_path):
    runtime, document = _runtime_with_document(tmp_path)
    target = "input/input.json"

    def delete(task, call_number):
        (task.workspace_dir / target).unlink()

    forger = _engine("forger", on_execute=delete)
    result = _run(runtime, document, forger)

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    errors = "\n".join(result.attempt_records[0].validation_errors)
    assert "missing" in errors
    assert target in errors

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    workspace = _workspace(runtime, result.task_id, "01-forger")
    assert not (workspace / target).exists()
    with pytest.raises(BundleIntegrityError, match="missing"):
        runtime.tasks.verify_workspace(task_dir, workspace)
    # The master template retains the deleted file.
    assert (task_dir / "bundle" / target).is_file()
    runtime.tasks.verify_bundle(task_dir)


def test_unexpected_extra_file_is_detected_post_execution(tmp_path):
    # Documented behavior: ANY unexpected file inside the immutable workspace
    # tree is an integrity failure today. Quarantine of legitimate unexpected
    # engine outputs is Milestone-B scope.
    runtime, document = _runtime_with_document(tmp_path)
    added = "input/resources/smuggled.md"

    def add(task, call_number):
        (task.workspace_dir / added).write_text("unexpected\n", encoding="utf-8")

    forger = _engine("forger", on_execute=add)
    result = _run(runtime, document, forger)

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    errors = "\n".join(result.attempt_records[0].validation_errors)
    assert "extra" in errors
    assert added in errors

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    workspace = _workspace(runtime, result.task_id, "01-forger")
    with pytest.raises(BundleIntegrityError, match="extra"):
        runtime.tasks.verify_workspace(task_dir, workspace)
    runtime.tasks.verify_bundle(task_dir)


def test_extra_resource_with_consistent_manifest_entry_is_still_detected(tmp_path):
    runtime, document = _runtime_with_document(tmp_path)
    added = "input/resources/RES0002/content.md"

    def add(task, call_number):
        workspace = task.workspace_dir
        target = workspace / added
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# smuggled resource\n", encoding="utf-8")
        manifest_path = workspace / "bundle_manifest.json"
        manifest_path.chmod(0o644)
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["resources"].append(
            {
                "resource_id": "RES0002",
                "logical_name": "smuggled.md",
                "path": added,
                "media_type": "text/markdown",
                "size_bytes": target.stat().st_size,
                "sha256": hash_file(target),
            }
        )
        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
            encoding="utf-8",
        )

    forger = _engine("forger", on_execute=add)
    result = _run(runtime, document, forger)

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    errors = "\n".join(result.attempt_records[0].validation_errors)
    assert "extra" in errors
    assert added in errors
    assert "bundle_manifest.json" in errors

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    workspace = _workspace(runtime, result.task_id, "01-forger")
    # The augmented manifest is self-consistent, yet the private expected set
    # still convicts the addition.
    assert _manifest_self_consistency_errors(workspace) == []
    with pytest.raises(BundleIntegrityError):
        runtime.tasks.verify_workspace(task_dir, workspace)
    runtime.tasks.verify_bundle(task_dir)


def test_symlink_planted_in_workspace_is_detected_post_execution(tmp_path):
    runtime, document = _runtime_with_document(tmp_path)

    def plant(task, call_number):
        (task.workspace_dir / "input" / "planted.md").symlink_to(document)

    forger = _engine("forger", on_execute=plant)
    result = _run(runtime, document, forger)

    assert result.outcome is AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE
    errors = "\n".join(result.attempt_records[0].validation_errors)
    assert "unexpected symlink" in errors

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    workspace = _workspace(runtime, result.task_id, "01-forger")
    assert (workspace / "input" / "planted.md").is_symlink()
    with pytest.raises(BundleIntegrityError, match="unexpected symlink"):
        runtime.tasks.verify_workspace(task_dir, workspace)
    runtime.tasks.verify_bundle(task_dir)


PRE_EXECUTION_TARGETS = [
    "bundle_manifest.json",
    "input/input.json",
    "contracts/input.schema.json",
    "input/resources/RES0001/content.md",
]


@pytest.mark.parametrize("target", PRE_EXECUTION_TARGETS)
def test_pre_execution_master_bundle_corruption_is_internal_failure(
    tmp_path, monkeypatch, target
):
    runtime, document = _runtime_with_document(tmp_path)
    original_create = runtime.tasks.create

    def corrupting_create(**kwargs):
        task_dir, manifest, provenance = original_create(**kwargs)
        path = task_dir / "bundle" / target
        path.chmod(0o644)
        path.write_text("corrupted before execution\n", encoding="utf-8")
        return task_dir, manifest, provenance

    monkeypatch.setattr(runtime.tasks, "create", corrupting_create)
    primary = _engine("primary")
    fallback = _engine("fallback")
    result = _run(runtime, document, primary, fallback)

    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    assert result.generation is None
    assert result.engine is None
    assert result.attempt_records == []
    assert primary.calls == 0
    assert fallback.calls == 0
    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    assert list((task_dir / "attempts").iterdir()) == []
    with pytest.raises(BundleIntegrityError):
        runtime.tasks.verify_bundle(task_dir)


def test_pre_execution_workspace_copy_corruption_is_internal_failure(
    tmp_path, monkeypatch
):
    runtime, document = _runtime_with_document(tmp_path)
    original_next_attempt = runtime.tasks.next_attempt

    def corrupting_next_attempt(task_dir, engine_name, task_type):
        attempt_dir, agent_task, attempt_id = original_next_attempt(
            task_dir, engine_name, task_type
        )
        target = agent_task.workspace_dir / "input" / "input.json"
        target.chmod(0o644)
        target.write_text("corrupted copy\n", encoding="utf-8")
        return attempt_dir, agent_task, attempt_id

    monkeypatch.setattr(runtime.tasks, "next_attempt", corrupting_next_attempt)
    primary = _engine("primary")
    fallback = _engine("fallback")
    result = _run(runtime, document, primary, fallback)

    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    assert result.generation is None
    assert result.engine is None
    assert result.attempt_records == []
    assert primary.calls == 0
    assert fallback.calls == 0

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    # The master template is intact: only the fresh attempt copy was corrupt.
    runtime.tasks.verify_bundle(task_dir)
    attempt_dir = task_dir / "attempts" / "01-primary"
    assert attempt_dir.is_dir()
    assert not (attempt_dir / "attempt_record.json").exists()
    assert not (attempt_dir / "agent_result.json").exists()


def test_private_trust_anchor_is_never_copied_into_attempt_workspaces(tmp_path):
    runtime, document = _runtime_with_document(tmp_path)

    def tamper(task, call_number):
        path = task.workspace_dir / "instructions.md"
        path.chmod(0o644)
        path.write_text("tampered by primary\n", encoding="utf-8")

    observed: dict[str, object] = {}

    def inspect(task, call_number):
        observed["task"] = task

    primary = _engine("primary", on_execute=tamper)
    fallback = _engine("fallback", on_execute=inspect)
    result = _run(runtime, document, primary, fallback)

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    anchor = task_dir / "private" / "task_provenance.json"
    assert anchor.is_file()

    # The engine-facing handle never points at private/.
    task = observed["task"]
    for field in (
        task.workspace_dir,
        task.instructions_path,
        task.input_dir,
        task.attempt_dir,
    ):
        assert "private" not in field.parts

    private_names = {
        "task_provenance.json",
        "invocation.json",
        "resource_sources.json",
    }
    provenance_keys = ("expected_bundle_manifest_hash", "expected_immutable_files")
    attempt_dirs = sorted((task_dir / "attempts").iterdir())
    assert [path.name for path in attempt_dirs] == ["01-primary", "02-fallback"]
    for attempt_dir in attempt_dirs:
        workspace = attempt_dir / "workspace"
        for path in workspace.rglob("*"):
            relative = path.relative_to(workspace)
            assert "private" not in relative.parts
            assert path.name not in private_names
            if path.is_file() and not path.is_symlink():
                text = path.read_text(encoding="utf-8")
                for key in provenance_keys:
                    assert key not in text

    # The clean fallback workspace is exactly the master bundle: nothing from
    # private/ was added and nothing from bundle/ was lost.
    master = task_dir / "bundle"
    fallback_workspace = _workspace(runtime, result.task_id, "02-fallback")
    master_files = {
        path.relative_to(master).as_posix()
        for path in master.rglob("*")
        if path.is_file()
    }
    fallback_files = {
        path.relative_to(fallback_workspace).as_posix()
        for path in fallback_workspace.rglob("*")
        if path.is_file()
    }
    assert fallback_files == master_files
