from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

import pytest

from vibereview.runtime import (
    AttemptOutcome,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    SubprocessEngine,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.execution import ProcessQuiescenceResult

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

VALID_PROPOSAL = {
    "themes": [
        {
            "local_ref": "theme_1",
            "title": "Thermal management",
            "description": "Generated by deterministic fixture",
            "origin": "generated",
            "parent_ref": None,
        }
    ],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "theme_1",
            "candidate_claim": "Preheating changes residual stress.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}


def _engine(name: str, *, modes: tuple[str, ...], execution_root_parent: Path | None = None) -> SubprocessEngine:
    policy = deterministic_test_policy()
    policy = policy.model_copy(update={"timeout_seconds": 15.0, "terminate_grace_seconds": 0.5})
    return SubprocessEngine(
        worker_script=WORKER,
        modes=modes,
        proposal_payloads={
            "valid_proposal.json": json.dumps(VALID_PROPOSAL).encode("utf-8")
        },
        name=name,
        policy=policy,
        execution_root_parent=execution_root_parent,
    )


def _run(runtime: ProjectRuntime, engine: SubprocessEngine, fallback_engine: SubprocessEngine | None = None):
    engines = [engine] if fallback_engine is None else [engine, fallback_engine]
    return runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
        engines=engines,
    )


def test_parent_exits_zero_with_no_child_normal_proposal(tmp_path: Path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="test")
    engine = _engine("clean", modes=("valid",), execution_root_parent=tmp_path / "exec-roots")
    result = _run(runtime, engine)
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    record = result.attempt_records[-1]
    assert record.accepted_attempt
    report = runtime.project_root / record.agent_result_path
    assert report.exists()
    assert result.transition is not None
    assert result.transition.canonicalized


def test_parent_exits_zero_and_leaves_child(tmp_path: Path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="test")
    engine = _engine(
        "surviving-child",
        modes=("valid", "spawn_child_then_exit_zero"),
        execution_root_parent=tmp_path / "exec-roots",
    )
    fallback = _engine("fallback", modes=("valid",), execution_root_parent=tmp_path / "exec-roots")
    result = _run(runtime, engine, fallback_engine=fallback)

    # First attempt must fail with ENGINE_EXECUTION_FAILURE, background_processes_survived_parent
    assert len(result.attempt_records) == 2
    first_record = result.attempt_records[0]
    assert first_record.outcome is AttemptOutcome.ENGINE_EXECUTION_FAILURE
    assert not first_record.accepted_attempt
    failure_codes = {f.code for f in first_record.detected_failures}
    assert "background_processes_survived_parent" in failure_codes

    # Fallback succeeded
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.attempt_records[1].accepted_attempt


def test_child_ignores_sigterm_escalates_to_sigkill(tmp_path: Path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="test")
    engine = _engine(
        "sigterm-ignored",
        modes=("valid", "child_ignores_sigterm_then_parent_exits"),
        execution_root_parent=tmp_path / "exec-roots",
    )
    result = _run(runtime, engine)
    first_record = result.attempt_records[0]
    assert first_record.outcome is AttemptOutcome.ENGINE_EXECUTION_FAILURE
    failure_codes = {f.code for f in first_record.detected_failures}
    assert "background_processes_survived_parent" in failure_codes


def test_quiescence_inspection_fails_internally(tmp_path: Path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="test")
    engine = _engine(
        "quiesce-fails",
        modes=("valid",),
        execution_root_parent=tmp_path / "exec-roots",
    )
    fallback = _engine("fallback", modes=("valid",), execution_root_parent=tmp_path / "exec-roots")

    with patch(
        "vibereview.runtime.execution.count_process_group_members",
        side_effect=OSError("procfs simulated failure"),
    ):
        result = _run(runtime, engine, fallback_engine=fallback)

    # Must be INTERNAL_RUNTIME_FAILURE, no fallback invoked!
    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    failure_codes = {f.code for f in record.detected_failures}
    assert "quiescence_inspection_failed" in failure_codes


def test_child_writes_after_parent_exit_never_imported(tmp_path: Path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="test")
    engine = _engine(
        "child-writer",
        modes=("child_writes_after_parent_exit",),
        execution_root_parent=tmp_path / "exec-roots",
    )
    result = _run(runtime, engine)
    assert result.outcome is AttemptOutcome.ENGINE_EXECUTION_FAILURE
    record = result.attempt_records[0]
    assert not record.accepted_attempt
    failure_codes = {f.code for f in record.detected_failures}
    assert "background_processes_survived_parent" in failure_codes
