"""TaskSpec ownership of dependencies and resources at the public runtime API.

Covers goal.md section 4 "TaskSpec ownership": the public ``ProjectRuntime.run``
API no longer accepts caller-controlled dependency selection (A1), dependencies
and resources are derived by the registered TaskSpec end-to-end, claim-keyed
objects are addressed by type-qualified keys, missing required dependencies
fail before engine invocation, and unimplemented task types fail before
task-ID allocation, workspace creation and engine invocation (A12).
"""

from __future__ import annotations

import inspect
import json
import re

import pytest

from vibereview.runtime import (
    TASK_SPECS,
    AggregatePaperEvidenceInvocation,
    AssessClaimInvocation,
    AssessEvidenceInvocation,
    AttemptOutcome,
    AuditPropositionInvocation,
    AuditRenderedSentenceInvocation,
    CandidateClaimProposal,
    ClaimAssessmentProposal,
    CorpusChallengerInvocation,
    DiscoveryProposalBundle,
    GenerateCandidateClaimsInvocation,
    GeneratePropositionsInvocation,
    GenerateRetrievalQueriesInvocation,
    MockEngine,
    MockResponse,
    ParseDeepResearchInvocation,
    ProjectRuntime,
    RenderProseInvocation,
    RepositorySnapshot,
    ReviseClaimInvocation,
    TaskType,
    TaskWorkspace,
    ThemeProposal,
    ValidateFinalClaimInvocation,
    executable_task_types,
)

UNIMPLEMENTED_TASK_TYPES = tuple(
    sorted(
        set(TaskType) - set(executable_task_types()),
        key=lambda task_type: task_type.value,
    )
)


def _positive_proposal() -> DiscoveryProposalBundle:
    return DiscoveryProposalBundle(
        themes=[
            ThemeProposal(
                local_ref="theme_1",
                title="Thermal management",
                description="Generated by deterministic fixture",
                origin="generated",
            )
        ],
        claims=[
            CandidateClaimProposal(
                local_ref="theme_claim_1",
                theme_ref="theme_1",
                candidate_claim="Preheating changes residual stress.",
                origin="generated",
                origin_refs=[],
            )
        ],
    )


def _reject_assessment_proposal() -> ClaimAssessmentProposal:
    return ClaimAssessmentProposal(
        claim_ref="C0001",
        aggregate_strength="low",
        evidence_sufficiency="insufficient",
        decision="REJECT",
        rejection_basis="insufficient_evidence",
        support_summary="Insufficient.",
        contradiction_summary="None.",
        qualification_summary="None.",
        reason="Evidence is insufficient.",
    )


def _snapshot_ready_for_claim_assessment(bundle_factory) -> RepositorySnapshot:
    bundle = bundle_factory()
    for name in (
        "claim_assessments",
        "final_claim_validations",
        "claim_packets",
        "proposition_records",
        "semantic_audits",
        "rendered_sentences",
        "rendered_sentence_audits",
    ):
        bundle[name] = []
    return RepositorySnapshot.model_validate(bundle)


def _minimal_invocation(task_type: TaskType):
    return {
        TaskType.PARSE_DEEP_RESEARCH: ParseDeepResearchInvocation(
            topic="residual stress", document_paths=[]
        ),
        TaskType.CORPUS_CHALLENGER: CorpusChallengerInvocation(
            topic="residual stress", paper_ids=[]
        ),
        TaskType.GENERATE_CANDIDATE_CLAIMS: GenerateCandidateClaimsInvocation(
            topic="residual stress", existing_theme_ids=[]
        ),
        TaskType.GENERATE_RETRIEVAL_QUERIES: GenerateRetrievalQueriesInvocation(
            claim_ids=[]
        ),
        TaskType.ASSESS_EVIDENCE: AssessEvidenceInvocation(
            claim_id="C0001", span_ids=[]
        ),
        TaskType.AGGREGATE_PAPER_EVIDENCE: AggregatePaperEvidenceInvocation(
            claim_id="C0001", paper_id="P0001", evidence_ids=[]
        ),
        TaskType.ASSESS_CLAIM: AssessClaimInvocation(
            claim_id="C0001", claim_paper_evidence_ids=[]
        ),
        TaskType.REVISE_CLAIM: ReviseClaimInvocation(
            claim_id="C0001", current_candidate_claim="Preheating reduces stress."
        ),
        TaskType.VALIDATE_FINAL_CLAIM: ValidateFinalClaimInvocation(
            claim_id="C0001",
            proposed_final_claim="Preheating reduced stress in the tested window.",
        ),
        TaskType.GENERATE_PROPOSITIONS: GeneratePropositionsInvocation(
            claim_ids=[]
        ),
        TaskType.AUDIT_PROPOSITION: AuditPropositionInvocation(
            proposition_id="PR0001"
        ),
        TaskType.RENDER_PROSE: RenderProseInvocation(proposition_ids=[]),
        TaskType.AUDIT_RENDERED_SENTENCE: AuditRenderedSentenceInvocation(
            sentence_id="RS0001"
        ),
    }[task_type]


def _task_names(runtime: ProjectRuntime) -> list[str]:
    tasks_root = runtime.project_root / "work" / "tasks"
    if not tasks_root.exists():
        return []
    return sorted(path.name for path in tasks_root.glob("TASK*"))


def test_public_run_signature_excludes_caller_controlled_dependencies():
    parameters = inspect.signature(ProjectRuntime.run).parameters
    assert "dependency_ids" not in parameters
    assert "dependencies" not in parameters
    assert not any(
        parameter.kind is inspect.Parameter.VAR_KEYWORD
        for parameter in parameters.values()
    )


def test_invocation_dtos_have_no_dependency_selection_fields():
    for spec in TASK_SPECS.values():
        assert "dependency_ids" not in spec.invocation_model.model_fields
        assert "dependencies" not in spec.invocation_model.model_fields


def test_passing_dependency_ids_to_run_raises_type_error(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="ownership")
    engine = MockEngine(
        [MockResponse(proposal=_positive_proposal().model_dump(mode="json"))]
    )
    with pytest.raises(TypeError, match="dependency_ids"):
        runtime.run(
            TaskType.GENERATE_CANDIDATE_CLAIMS,
            GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
            engines=[engine],
            dependency_ids=["CandidateClaim:C0001"],
        )
    assert engine.calls == 0
    assert _task_names(runtime) == []
    assert runtime.store.current_generation() == 0


def test_spec_derived_dependencies_are_snapshotted_end_to_end(
    tmp_path, bundle_factory
):
    snapshot = _snapshot_ready_for_claim_assessment(bundle_factory)
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="dependencies", initial_snapshot=snapshot
    )
    invocation = AssessClaimInvocation(
        claim_id="C0001", claim_paper_evidence_ids=["CPE-C0001-P0001"]
    )
    spec = TASK_SPECS[TaskType.ASSESS_CLAIM]
    expected_keys = spec.dependency_builder(invocation, snapshot)
    assert expected_keys == (
        "CandidateClaim:C0001",
        "ClaimPaperEvidence:CPE-C0001-P0001",
    )
    engine = MockEngine(
        [MockResponse(proposal=_reject_assessment_proposal().model_dump(mode="json"))]
    )
    result = runtime.run(TaskType.ASSESS_CLAIM, invocation, engines=[engine])
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert engine.calls == 1

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    provenance = TaskWorkspace.load_provenance(task_dir)
    manifest = TaskWorkspace.load_manifest(task_dir)
    # The private trust anchor and the task manifest record exactly the
    # qualified keys the TaskSpec dependency builder returned: none added,
    # none omitted, none selectable by the caller.
    assert tuple(provenance.dependencies) == expected_keys
    assert tuple(manifest.dependencies) == expected_keys
    for key in expected_keys:
        assert provenance.dependencies[key] == snapshot.dependency_hash(key)

    dependency_dir = task_dir / "bundle" / "input" / "dependencies"
    expected_files = sorted(f"{key.replace(':', '__')}.json" for key in expected_keys)
    assert sorted(path.name for path in dependency_dir.iterdir()) == expected_files
    for key, filename in zip(expected_keys, sorted(expected_files), strict=True):
        assert f"input/dependencies/{filename}" in provenance.expected_immutable_files
        assert provenance.expected_immutable_files[f"input/dependencies/{filename}"]
        assert key.split(":", 1)[0] in filename

    candidate_payload = json.loads(
        (dependency_dir / "CandidateClaim__C0001.json").read_text(encoding="utf-8")
    )
    assert candidate_payload == json.loads(
        snapshot.candidate_claims[0].model_dump_json()
    )
    cpe_payload = json.loads(
        (dependency_dir / "ClaimPaperEvidence__CPE-C0001-P0001.json").read_text(
            encoding="utf-8"
        )
    )
    assert cpe_payload == json.loads(snapshot.claim_paper_evidence[0].model_dump_json())


def test_claim_keyed_qualified_keys_resolve_to_distinct_objects(bundle_factory):
    snapshot = RepositorySnapshot.model_validate(bundle_factory())
    index = snapshot.object_index()
    qualified_keys = (
        "CandidateClaim:C0001",
        "ClaimAssessment:C0001",
        "FinalClaimValidation:C0001",
        "ClaimPacket:C0001",
    )
    resolved = [index.get(key) for key in qualified_keys]
    assert all(value is not None for value in resolved)
    assert [type(value).__name__ for value in resolved] == [
        "CandidateClaim",
        "ClaimAssessment",
        "FinalClaimValidation",
        "ClaimPacket",
    ]
    hashes = {key: snapshot.dependency_hash(key) for key in qualified_keys}
    # One shared claim_id still yields distinct typed dependency anchors.
    assert len(set(hashes.values())) == len(qualified_keys)
    # The bare shared identifier is ambiguous by construction: it resolves to
    # exactly one class, which is why dependency builders must qualify keys.
    bare = index["C0001"]
    assert type(bare).__name__ == "CandidateClaim"
    assert bare is index["CandidateClaim:C0001"]
    assert bare is not index["ClaimAssessment:C0001"]


@pytest.mark.parametrize(
    ("invocation", "missing_key"),
    [
        (
            AssessClaimInvocation(
                claim_id="C0002",
                claim_paper_evidence_ids=["CPE-C0001-P0001"],
            ),
            "CandidateClaim:C0002",
        ),
        (
            AssessClaimInvocation(
                claim_id="C0001",
                claim_paper_evidence_ids=["CPE-C0001-P0002"],
            ),
            "ClaimPaperEvidence:CPE-C0001-P0002",
        ),
    ],
    ids=["missing-claim", "missing-claim-paper-evidence"],
)
def test_missing_required_dependency_fails_before_engine_invocation(
    tmp_path, bundle_factory, invocation, missing_key
):
    snapshot = _snapshot_ready_for_claim_assessment(bundle_factory)
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="missing", initial_snapshot=snapshot
    )
    engine = MockEngine(
        [MockResponse(proposal=_reject_assessment_proposal().model_dump(mode="json"))]
    )
    with pytest.raises(KeyError, match=re.escape(missing_key)):
        runtime.run(TaskType.ASSESS_CLAIM, invocation, engines=[engine])
    assert engine.calls == 0
    assert _task_names(runtime) == []
    assert runtime.store.current_generation() == 0


def test_parse_deep_research_resources_are_generated_from_task_spec(tmp_path):
    project = tmp_path / "project"
    documents_dir = project / "input" / "deep_research"
    documents_dir.mkdir(parents=True)
    documents = []
    for name in ("alpha.md", "beta.md", "gamma.md"):
        path = documents_dir / name
        path.write_text(f"# {name}\n\nBody of {name}.\n", encoding="utf-8")
        documents.append(path)
    runtime = ProjectRuntime.create(project, project_name="resources")
    engine = MockEngine(
        [MockResponse(proposal=_positive_proposal().model_dump(mode="json"))]
    )
    result = runtime.run(
        TaskType.PARSE_DEEP_RESEARCH,
        ParseDeepResearchInvocation(topic="residual stress", document_paths=documents),
        engines=[engine],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    provenance = TaskWorkspace.load_provenance(task_dir)
    expected_ids = ["RES0001", "RES0002", "RES0003"]
    # Exactly one generated RES entry per document path; the caller supplied
    # only document paths, never resource IDs.
    assert [entry.resource_id for entry in provenance.resources] == expected_ids
    assert [entry.logical_name for entry in provenance.resources] == [
        "alpha.md",
        "beta.md",
        "gamma.md",
    ]
    sources = json.loads(
        (task_dir / "private" / "resource_sources.json").read_text(encoding="utf-8")
    )
    assert [entry["resource_id"] for entry in sources] == expected_ids
    assert [entry["logical_name"] for entry in sources] == [
        "alpha.md",
        "beta.md",
        "gamma.md",
    ]
    assert all(entry["source_path"] for entry in sources)

    resources_root = task_dir / "bundle" / "input" / "resources"
    assert sorted(path.name for path in resources_root.iterdir()) == expected_ids
    for resource_id, source in zip(expected_ids, documents, strict=True):
        copied = resources_root / resource_id / "content.md"
        assert copied.is_file()
        assert copied.read_bytes() == source.read_bytes()

    engine_input = json.loads(
        (task_dir / "bundle" / "input" / "input.json").read_text(encoding="utf-8")
    )
    assert engine_input == {
        "topic": "residual stress",
        "document_resource_ids": expected_ids,
    }
    manifest = json.loads(
        (task_dir / "bundle" / "bundle_manifest.json").read_text(encoding="utf-8")
    )
    assert [entry["resource_id"] for entry in manifest["resources"]] == expected_ids


def test_task_without_resources_has_empty_resource_surfaces(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="no-resources")
    engine = MockEngine(
        [MockResponse(proposal=_positive_proposal().model_dump(mode="json"))]
    )
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
        engines=[engine],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    provenance = TaskWorkspace.load_provenance(task_dir)
    assert provenance.resources == ()
    resources_root = task_dir / "bundle" / "input" / "resources"
    assert resources_root.is_dir()
    assert list(resources_root.iterdir()) == []
    manifest = json.loads(
        (task_dir / "bundle" / "bundle_manifest.json").read_text(encoding="utf-8")
    )
    assert manifest["resources"] == []
    sources = json.loads(
        (task_dir / "private" / "resource_sources.json").read_text(encoding="utf-8")
    )
    assert sources == []

    raw_input = (task_dir / "bundle" / "input" / "input.json").read_text(
        encoding="utf-8"
    )
    payload = json.loads(raw_input)
    assert payload == {"topic": "stress", "existing_theme_ids": []}
    assert not any("resource" in key for key in payload)
    assert re.search(r"RES[0-9]{4,}", raw_input) is None

    workspace_resources = (
        task_dir / "attempts" / "01-mock" / "workspace" / "input" / "resources"
    )
    assert workspace_resources.is_dir()
    assert list(workspace_resources.iterdir()) == []


@pytest.mark.parametrize(
    "task_type",
    UNIMPLEMENTED_TASK_TYPES,
    ids=[task_type.value for task_type in UNIMPLEMENTED_TASK_TYPES],
)
def test_unimplemented_task_types_fail_before_engine_invocation_and_allocation(
    tmp_path, task_type
):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="unimplemented")
    engine = MockEngine([], name="strict-mock")
    result = runtime.run(
        task_type, _minimal_invocation(task_type), engines=[engine]
    )
    assert result.outcome is AttemptOutcome.TASK_TYPE_NOT_IMPLEMENTED
    assert result.task_id == ""
    assert result.generation is None
    assert result.attempt_records == []
    assert engine.calls == 0
    assert _task_names(runtime) == []
    assert runtime.store.current_generation() == 0


def test_unimplemented_task_type_allocates_no_new_task_directory(tmp_path):
    assert UNIMPLEMENTED_TASK_TYPES, "registry should still list planned task types"
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="allocation")
    engine = MockEngine(
        [MockResponse(proposal=_positive_proposal().model_dump(mode="json"))]
    )
    first = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
        engines=[engine],
    )
    assert first.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    before = _task_names(runtime)
    assert before == ["TASK0001"]

    strict = MockEngine([], name="strict-mock")
    task_type = UNIMPLEMENTED_TASK_TYPES[0]
    result = runtime.run(
        task_type, _minimal_invocation(task_type), engines=[strict]
    )
    assert result.outcome is AttemptOutcome.TASK_TYPE_NOT_IMPLEMENTED
    assert strict.calls == 0
    assert _task_names(runtime) == before
    assert runtime.store.current_generation() == 1
