"""Subprocess fallback, REJECT canonicalization and state preservation (§7.14).

The deterministic fake worker runs as a real OS process through
``SubprocessEngine``. These tests prove the frozen §6.6 outcomes reach the
kernel intact, a technical failure never mutates canonical state, a fallback
engine receives a workspace byte-identical to the private trust anchor, and a
contract-valid REJECT assessment is canonicalized without engine fallback.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vibereview.runtime import (
    AssessClaimInvocation,
    AttemptFailureStage,
    AttemptOutcome,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    RepositorySnapshot,
    SubprocessEngine,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.subprocess import SubprocessPolicy

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

# Contract-valid ClaimAssessmentProposal with decision REJECT: a scientific
# result that must be canonicalized and must never trigger fallback (§4.5).
REJECT_PROPOSAL = {
    "claim_ref": "C0001",
    "aggregate_strength": "low",
    "evidence_sufficiency": "insufficient",
    "decision": "REJECT",
    "rejection_basis": "insufficient_evidence",
    "support_summary": "Insufficient.",
    "contradiction_summary": "None.",
    "qualification_summary": "None.",
    "reason": "Evidence is insufficient.",
}

# Schema-valid DiscoveryProposalBundle whose theme_ref is neither proposal-local
# nor canonical: passes Pydantic, fails task-level proposal validation.
TASK_INVALID_PROPOSAL = {
    "themes": [],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "unknown_theme",
            "candidate_claim": "Claim without a known theme.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}


def _json_bytes(payload: dict) -> bytes:
    return (json.dumps(payload) + "\n").encode("utf-8")


def _discovery_payload() -> bytes:
    return _json_bytes(
        {
            "themes": [
                {
                    "local_ref": "theme_1",
                    "title": "Thermal management",
                    "description": "Generated by deterministic fixture",
                    "origin": "generated",
                    "parent_ref": None,
                }
            ],
            "claims": [
                {
                    "local_ref": "claim_1",
                    "theme_ref": "theme_1",
                    "candidate_claim": "Preheating changes residual stress.",
                    "origin": "generated",
                    "origin_refs": [],
                }
            ],
        }
    )


def _engine(
    name: str,
    modes: tuple[str, ...],
    *,
    payloads: dict[str, bytes] | None = None,
    policy: SubprocessPolicy | None = None,
) -> SubprocessEngine:
    return SubprocessEngine(
        worker_script=WORKER,
        modes=modes,
        proposal_payloads=payloads,
        name=name,
        policy=policy,
    )


def _runtime(tmp_path: Path) -> ProjectRuntime:
    return ProjectRuntime.create(tmp_path / "project", project_name="fallback")


def _run_discovery(runtime: ProjectRuntime, engines: list[SubprocessEngine]):
    return runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
        engines=engines,
    )


def _task_dir(runtime: ProjectRuntime, task_id: str) -> Path:
    return runtime.project_root / "work" / "tasks" / task_id


def _tree_bytes(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _execution_report(runtime: ProjectRuntime, record) -> dict:
    path = runtime.project_root / record.agent_result_path
    return json.loads(path.read_text(encoding="utf-8"))["execution_report"]


def _generation_names(runtime: ProjectRuntime) -> list[str]:
    generations = runtime.project_root / "state" / "generations"
    return sorted(path.name for path in generations.iterdir() if path.is_dir())


def _snapshot_without_downstream_claim_objects(bundle_factory) -> RepositorySnapshot:
    bundle = bundle_factory()
    for name in (
        "claim_assessments",
        "final_claim_validations",
        "claim_packets",
        "proposition_records",
        "semantic_audits",
        "rendered_sentences",
        "rendered_sentence_audits",
    ):
        bundle[name] = []
    return RepositorySnapshot.model_validate(bundle)


def test_tampering_primary_fails_integrity_and_fallback_gets_pristine_workspace(
    tmp_path,
):
    runtime = _runtime(tmp_path)
    primary = _engine("fake-primary", ("tamper_instructions",))
    fallback = _engine(
        "fake-fallback",
        ("valid",),
        payloads={"valid_proposal.json": _discovery_payload()},
    )
    result = _run_discovery(runtime, [primary, fallback])

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    assert [record.engine for record in result.attempt_records] == [
        "fake-primary",
        "fake-fallback",
    ]
    tampered, accepted = result.attempt_records
    assert tampered.attempt_id == "01-fake-primary"
    assert accepted.attempt_id == "02-fake-fallback"
    assert tampered.accepted_attempt is False
    failure = next(
        failure
        for failure in tampered.detected_failures
        if failure.code == "bundle_integrity_mismatch"
    )
    assert failure.stage is AttemptFailureStage.WORKSPACE
    report = _execution_report(runtime, tampered)
    assert report["bundle_modified"] is True
    assert report["primary_outcome"] == "engine_workspace_integrity_failure"

    # The generation is committed exactly once, by the fallback attempt.
    assert result.generation == 1
    assert runtime.store.current_generation() == 1
    assert _generation_names(runtime) == ["000000", "000001"]
    assert accepted.accepted_attempt
    assert accepted.output_hash is not None

    task_dir = _task_dir(runtime, result.task_id)
    assert (task_dir / "private" / "task_provenance.json").is_file()
    assert (task_dir / "accepted" / "proposal.json").is_file()
    for record in result.attempt_records:
        attempt_dir = task_dir / "attempts" / record.attempt_id
        assert (attempt_dir / "attempt_record.json").is_file()
        assert (attempt_dir / "agent_result.json").is_file()
    assert not (
        task_dir / "attempts" / tampered.attempt_id / "proposal.json"
    ).exists()
    assert (
        task_dir / "attempts" / accepted.attempt_id / "proposal.json"
    ).is_file()

    # The fallback attempt received a fresh workspace that stayed
    # byte-identical to the master bundle; both workspaces and the bundle
    # still verify against the private trust anchor. The primary's tampering
    # never left its (already deleted) external execution root.
    fallback_workspace = task_dir / "attempts" / accepted.attempt_id / "workspace"
    assert _tree_bytes(fallback_workspace) == _tree_bytes(task_dir / "bundle")
    runtime.tasks.verify_bundle(task_dir)
    runtime.tasks.verify_workspace(task_dir, fallback_workspace)
    runtime.tasks.verify_workspace(
        task_dir, task_dir / "attempts" / tampered.attempt_id / "workspace"
    )


@pytest.mark.parametrize(
    ("mode", "policy_update", "outcome", "code", "stage"),
    [
        (
            "nonzero",
            {},
            AttemptOutcome.ENGINE_EXECUTION_FAILURE,
            "process_nonzero_exit",
            AttemptFailureStage.PROCESS,
        ),
        (
            "timeout",
            {"timeout_seconds": 0.8, "terminate_grace_seconds": 0.3},
            AttemptOutcome.ENGINE_EXECUTION_FAILURE,
            "process_timeout",
            AttemptFailureStage.PROCESS,
        ),
        (
            "missing_proposal",
            {},
            AttemptOutcome.ENGINE_FORMAT_FAILURE,
            "proposal_missing",
            AttemptFailureStage.PROPOSAL_FILE,
        ),
        (
            "tamper_input",
            {},
            AttemptOutcome.ENGINE_WORKSPACE_INTEGRITY_FAILURE,
            "bundle_integrity_mismatch",
            AttemptFailureStage.WORKSPACE,
        ),
        (
            "extra_output",
            {},
            AttemptOutcome.ENGINE_OUTPUT_POLICY_FAILURE,
            "unexpected_output_file",
            AttemptFailureStage.OUTPUT_TREE,
        ),
        (
            "large_scratch_file",
            {},
            AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE,
            "max_writable_single_file_bytes",
            AttemptFailureStage.RESOURCE_LIMIT,
        ),
    ],
    ids=[
        "nonzero",
        "timeout",
        "missing_proposal",
        "tamper_input",
        "extra_output",
        "large_scratch_file",
    ],
)
def test_technical_failure_preserves_canonical_state(
    tmp_path, mode, policy_update, outcome, code, stage
):
    runtime = _runtime(tmp_path)
    _, snapshot_before, _ = runtime.store.load_current()
    engine = _engine(
        "fake-broken",
        (mode,),
        policy=deterministic_test_policy().model_copy(update=policy_update),
    )
    result = _run_discovery(runtime, [engine])

    assert result.outcome is outcome
    assert result.generation is None
    assert result.transition is None
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is outcome
    assert record.accepted_attempt is False
    # Runner-classified failure: detected at the subprocess boundary, so the
    # kernel-stage flags stay False/None and the defects are itemized.
    assert record.format_valid is False
    assert record.schema_valid is False
    assert record.proposal_validation_valid is None
    assert record.output_hash is None
    assert record.validation_errors
    detected = {(failure.code, failure.stage) for failure in record.detected_failures}
    assert (code, stage) in detected
    report = _execution_report(runtime, record)
    assert report["primary_outcome"] == outcome.value
    assert report["confinement_level"] == "test_only"
    if mode == "nonzero":
        assert report["exit_code"] == 3
    if mode == "timeout":
        assert report["timed_out"] is True
        assert report["exit_code"] != 0
        assert report["execution_root"] is not None
        assert not Path(report["execution_root"]).exists()

    # Canonical state is untouched: no commit, no accepted proposal.
    assert runtime.store.current_generation() == 0
    assert _generation_names(runtime) == ["000000"]
    assert runtime.store.load_current()[1] == snapshot_before
    task_dir = _task_dir(runtime, result.task_id)
    assert not (task_dir / "accepted" / "proposal.json").exists()


def test_valid_reject_is_canonicalized_without_fallback_or_claim_packet(
    tmp_path, bundle_factory
):
    snapshot = _snapshot_without_downstream_claim_objects(bundle_factory)
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="reject", initial_snapshot=snapshot
    )
    primary = _engine(
        "fake-primary",
        ("valid",),
        payloads={"valid_proposal.json": _json_bytes(REJECT_PROPOSAL)},
    )
    fallback = _engine(
        "fake-fallback",
        ("valid",),
        payloads={
            "valid_proposal.json": _json_bytes(
                {**REJECT_PROPOSAL, "reason": "Fallback engine must never run."}
            )
        },
    )
    result = runtime.run(
        TaskType.ASSESS_CLAIM,
        AssessClaimInvocation(
            claim_id="C0001",
            claim_paper_evidence_ids=["CPE-C0001-P0001"],
        ),
        engines=[primary, fallback],
    )

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    assert result.transition is not None
    assert result.transition.scientific_disposition == "REJECT"
    assert result.transition.canonicalized
    assert not result.transition.downstream_eligible

    # REJECT is a scientific result: the fallback engine was never invoked.
    assert result.engine == "fake-primary"
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert record.accepted_attempt
    task_dir = _task_dir(runtime, result.task_id)
    assert [path.name for path in (task_dir / "attempts").iterdir()] == [
        record.attempt_id
    ]

    _, current, _ = runtime.store.load_current()
    assert len(current.claim_assessments) == 1
    assessment = current.claim_assessments[0]
    assert assessment.claim_id == "C0001"
    assert assessment.decision.value == "REJECT"
    assert assessment.rejection_basis.value == "insufficient_evidence"
    assert assessment.reason == "Evidence is insufficient."
    assert current.claim_packets == ()
    assert current.final_claim_validations == ()


@pytest.mark.parametrize(
    ("mode", "payload", "outcome", "flags"),
    [
        (
            "schema_invalid",
            _json_bytes({"unexpected": True}),
            AttemptOutcome.ENGINE_SCHEMA_FAILURE,
            (True, False, None),
        ),
        (
            "proposal_invalid",
            _json_bytes(TASK_INVALID_PROPOSAL),
            AttemptOutcome.ENGINE_PROPOSAL_VALIDATION_FAILURE,
            (True, True, False),
        ),
    ],
    ids=["schema_invalid", "proposal_invalid"],
)
def test_kernel_stage_failure_reaches_fallback_engine(
    tmp_path, mode, payload, outcome, flags
):
    runtime = _runtime(tmp_path)
    primary = _engine(
        "fake-primary",
        (mode,),
        payloads={f"{mode}_proposal.json": payload},
    )
    fallback = _engine(
        "fake-fallback",
        ("valid",),
        payloads={"valid_proposal.json": _discovery_payload()},
    )
    result = _run_discovery(runtime, [primary, fallback])

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    assert [record.outcome for record in result.attempt_records] == [
        outcome,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    failed, accepted = result.attempt_records
    format_valid, schema_valid, proposal_valid = flags
    # Kernel-stage failure: nothing detected at the subprocess boundary, the
    # staged flags show how far the proposal progressed, and the validation
    # errors carry the reason.
    assert failed.format_valid is format_valid
    assert failed.schema_valid is schema_valid
    assert failed.proposal_validation_valid is proposal_valid
    assert failed.detected_failures == ()
    assert failed.validation_errors
    assert failed.accepted_attempt is False
    assert accepted.accepted_attempt

    task_dir = _task_dir(runtime, result.task_id)
    failed_dir = task_dir / "attempts" / failed.attempt_id
    assert (failed_dir / "proposal.json").is_file()
    assert (task_dir / "accepted" / "proposal.json").is_file()

    _, snapshot, _ = runtime.store.load_current()
    assert [claim.claim_id for claim in snapshot.candidate_claims] == ["C0001"]
