from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from vibereview.runtime import (
    AttemptOutcome,
    ConfinementLevel,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    RuntimeConfig,
    SubprocessAgentResult,
    SubprocessEngine,
    TaskType,
    deterministic_test_policy,
)

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

VALID_PROPOSAL = {
    "themes": [
        {
            "local_ref": "theme_1",
            "title": "Thermal management",
            "description": "Generated by deterministic fixture",
            "origin": "generated",
            "parent_ref": None,
        }
    ],
    "claims": [
        {
            "local_ref": "claim_1",
            "theme_ref": "theme_1",
            "candidate_claim": "Preheating changes residual stress.",
            "origin": "generated",
            "origin_refs": [],
        }
    ],
}

# The fake worker has no environment-dump mode, so the §7.5 assertions use a
# test-local probe worker that echoes its argv, cwd and environment on stdout
# (persisted as attempt/stdout.txt) and then stages the valid proposal exactly
# like the fake worker's "valid" mode.
_ENV_PROBE_SOURCE = '''#!/usr/bin/env python3
import argparse
import json
import os
import shutil
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--mode", dest="modes", action="append", required=True)
    parser.parse_args()
    shutil.copyfile(
        Path("launcher") / "valid_proposal.json",
        Path("output") / "proposal.json",
    )
    payload = {
        "argv": sys.argv,
        "cwd": os.getcwd(),
        "env": dict(sorted(os.environ.items())),
    }
    sys.stdout.buffer.write(
        (json.dumps(payload, ensure_ascii=True, sort_keys=True) + "\\n").encode("ascii")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _engine(
    name: str,
    *,
    modes: tuple[str, ...] = ("valid",),
    worker_script: Path = WORKER,
) -> SubprocessEngine:
    return SubprocessEngine(
        worker_script=worker_script,
        modes=modes,
        proposal_payloads={
            "valid_proposal.json": json.dumps(VALID_PROPOSAL).encode("utf-8")
        },
        name=name,
        policy=deterministic_test_policy(),
    )


def _run(runtime: ProjectRuntime, engine: SubprocessEngine):
    return runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
        engines=[engine],
    )


def _load_agent_result(
    runtime: ProjectRuntime, record
) -> SubprocessAgentResult:
    path = runtime.project_root / record.agent_result_path
    return SubprocessAgentResult.model_validate_json(path.read_text(encoding="utf-8"))


def test_valid_proposal_commits_generation_and_updates_snapshot(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="exec")
    result = _run(runtime, _engine("fake-happy"))

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    assert runtime.store.current_generation() == 1
    assert result.allocated_ids == {"theme_1": "T0001", "claim_1": "C0001"}

    generation, snapshot, _ = runtime.store.load_current()
    assert generation == 1
    assert [theme.theme_id for theme in snapshot.themes] == ["T0001"]
    assert snapshot.themes[0].title == "Thermal management"
    assert [claim.claim_id for claim in snapshot.candidate_claims] == ["C0001"]
    assert snapshot.candidate_claims[0].theme_id == "T0001"

    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    assert record.task_id == result.task_id
    assert record.attempt_id == "01-fake-happy"
    assert record.engine == "fake-happy"
    assert record.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert record.format_valid
    assert record.schema_valid
    assert record.proposal_validation_valid is True
    assert record.accepted_attempt
    assert record.validation_errors == []
    assert record.detected_failures == ()
    assert record.output_hash is not None

    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    attempt_dir = task_dir / "attempts" / record.attempt_id
    assert (task_dir / "accepted" / "proposal.json").is_file()
    assert (attempt_dir / "attempt_record.json").is_file()
    assert (attempt_dir / "agent_result.json").is_file()
    assert (attempt_dir / "proposal.json").is_file()
    assert (attempt_dir / "stdout.txt").is_file()
    assert (attempt_dir / "stderr.txt").is_file()


def test_valid_attempt_execution_report_records_clean_test_only_run(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="report")
    result = _run(runtime, _engine("fake-report"))

    record = result.attempt_records[0]
    agent_result = _load_agent_result(runtime, record)
    report = agent_result.execution_report

    assert agent_result.execution_succeeded
    assert agent_result.execution_error is None
    assert record.agent_result_path == Path(
        "work/tasks",
        result.task_id,
        "attempts",
        record.attempt_id,
        "agent_result.json",
    )
    assert report.execution_root is not None
    assert report.exit_code == 0
    assert report.timed_out is False
    assert report.launch_error is None
    assert report.confinement_level is ConfinementLevel.TEST_ONLY
    assert report.confinement_level.value == "test_only"
    assert report.duration_seconds > 0
    assert report.primary_outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert not report.resource_limit_breached
    assert not report.bundle_modified
    assert not report.output_policy_violated
    assert not report.proposal_format_invalid
    assert report.detected_failures == ()
    assert report.stdout_capture.relative_path == Path("attempt/stdout.txt")
    assert report.stderr_capture.relative_path == Path("attempt/stderr.txt")


def test_execution_root_is_outside_project_and_removed_after_import(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="root")
    result = _run(runtime, _engine("fake-root"))

    report = _load_agent_result(runtime, result.attempt_records[0]).execution_report
    execution_root = report.execution_root
    assert execution_root is not None
    assert execution_root.name.startswith("vibereview-exec-")
    assert not execution_root.is_relative_to(runtime.project_root)
    assert not execution_root.exists()


def test_worker_receives_argv_vector_and_allowlisted_environment(
    tmp_path, monkeypatch
):
    monkeypatch.setenv("VIBEREVIEW_EXECUTION_TEST_CANARY", "parent-only")
    probe = tmp_path / "env_probe_worker.py"
    probe.write_text(_ENV_PROBE_SOURCE, encoding="utf-8")
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="env")
    result = _run(runtime, _engine("fake-env", worker_script=probe))
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT

    record = result.attempt_records[0]
    agent_result = _load_agent_result(runtime, record)
    report = agent_result.execution_report
    execution_root = report.execution_root
    assert execution_root is not None

    # goal.md §7.4: an argv vector executed without a shell.
    argv = list(report.argv)
    assert all(isinstance(element, str) for element in argv)
    assert argv[0] == sys.executable
    assert Path(argv[1]).name == "trusted_launcher.py"
    assert Path(argv[1]).parent == execution_root / "launcher"
    assert "--policy" in argv
    assert "--report" in argv
    assert "--" in argv
    inner_idx = argv.index("--") + 1
    assert argv[inner_idx] == sys.executable
    assert Path(argv[inner_idx + 1]).name == probe.name
    assert Path(argv[inner_idx + 1]).parent == execution_root / "launcher"

    observed = json.loads(agent_result.stdout)
    assert observed["argv"] == argv[inner_idx + 1:]
    assert observed["cwd"] == str(execution_root)
    environment = observed["env"]

    # goal.md §7.2: the review project (and therefore state/, task private/
    # and original input paths) appears in neither the command nor the
    # environment.
    project_root = str(runtime.project_root)
    assert all(project_root not in element for element in argv)
    assert all(project_root not in value for value in environment.values())

    # goal.md §7.5: only allowlisted inheritance plus isolated task paths.
    policy = deterministic_test_policy()
    allowed = set(policy.inherited_environment_allowlist) | {
        "HOME",
        "XDG_CONFIG_HOME",
        "XDG_CACHE_HOME",
        "TMPDIR",
    }
    assert set(environment) <= allowed
    assert "VIBEREVIEW_EXECUTION_TEST_CANARY" not in environment
    for name in policy.inherited_environment_allowlist:
        if name in os.environ:
            assert environment.get(name) == os.environ[name]
    assert environment["HOME"] == str(execution_root / "home")
    assert environment["XDG_CONFIG_HOME"] == str(execution_root / "home" / ".config")
    assert environment["XDG_CACHE_HOME"] == str(execution_root / "home" / ".cache")
    assert environment["TMPDIR"] == str(execution_root / "tmp")


def test_permitted_scratch_within_quota_is_valid(tmp_path):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="scratch")
    result = _run(runtime, _engine("fake-scratch", modes=("permitted_scratch",)))

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    record = result.attempt_records[0]
    assert record.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    report = _load_agent_result(runtime, record).execution_report
    assert report.exit_code == 0
    assert not report.resource_limit_breached
    assert not report.output_policy_violated
    assert report.detected_failures == ()

    inventory = {entry.relative_path: entry for entry in report.inventory}
    scratch_file = inventory[Path("scratch/ok.txt")]
    assert scratch_file.file_type == "regular"
    assert scratch_file.size_bytes == 1024
    assert scratch_file.content_hash is not None
    assert not any(
        str(runtime.project_root) in str(entry.relative_path)
        for entry in report.inventory
    )


def test_second_identical_run_hits_cache_without_worker_execution(tmp_path):
    runtime = ProjectRuntime.create(
        tmp_path / "project",
        project_name="cache",
        config=RuntimeConfig(enable_receipts=False),
    )
    engine = _engine("fake-cache")
    invocation = GenerateCandidateClaimsInvocation(
        topic="stress", existing_theme_ids=[]
    )

    first = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS, invocation, engines=[engine]
    )
    second = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS, invocation, engines=[engine]
    )

    assert first.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert second.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert first.generation == 1
    assert len(first.attempt_records) == 1
    assert len(second.attempt_records) == 1
    assert second.attempt_records[0].accepted_attempt

    def agent_result_payload(result) -> dict:
        path = runtime.project_root / result.attempt_records[0].agent_result_path
        return json.loads(path.read_text(encoding="utf-8"))

    # A cache hit never reaches SubprocessEngine.execute, so the second
    # attempt persists a plain AgentResult without an execution_report.
    assert "execution_report" in agent_result_payload(first)
    second_payload = agent_result_payload(second)
    assert "execution_report" not in second_payload
    assert second_payload["stdout"] == "cache hit\n"
