"""Writable-tree quota conformance through the subprocess runner (goal.md §7.10).

Covers the §6.5 writable-quota breach codes end to end through
``SubprocessEngine``: single-file size, file count, directory depth, tree
bytes and process count each yield ``ENGINE_RESOURCE_LIMIT_FAILURE`` with a
``resource_limit``-stage ``AttemptFailure``; a breach terminates the process
group instead of hanging; a scratch file within quota stays valid; and bundle
files are quota-exempt (§6.7), so a bundle resource larger than the
single-file quota is permitted.
"""

from __future__ import annotations

import json
import signal
from pathlib import Path

import pytest

from vibereview.runtime import (
    QUOTA_EXEMPT_ROOTS,
    WRITABLE_QUOTA_ROOTS,
    AttemptFailure,
    AttemptOutcome,
    GenerateCandidateClaimsInvocation,
    ParseDeepResearchInvocation,
    ProjectRuntime,
    ResourceLimitCode,
    RuntimeResult,
    SubprocessAgentResult,
    SubprocessEngine,
    SubprocessExecutionResult,
    TaskAttemptRecord,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.records import AttemptFailureStage
from vibereview.runtime.resource_limits import scan_writable_roots
from vibereview.runtime.subprocess import SubprocessPolicy

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

VALID_PROPOSAL = json.dumps(
    {
        "themes": [
            {
                "local_ref": "theme_1",
                "title": "Thermal management",
                "description": "Generated by the deterministic fake worker",
                "origin": "generated",
                "parent_ref": None,
            }
        ],
        "claims": [
            {
                "local_ref": "claim_1",
                "theme_ref": "theme_1",
                "candidate_claim": "Preheating changes residual stress.",
                "origin": "generated",
                "origin_refs": [],
            }
        ],
    }
).encode("utf-8")


def _policy(**overrides) -> SubprocessPolicy:
    return deterministic_test_policy().model_copy(update=overrides)


def _engine(
    name: str,
    modes: tuple[str, ...],
    *,
    worker_config: dict | None = None,
    policy: SubprocessPolicy | None = None,
) -> SubprocessEngine:
    return SubprocessEngine(
        worker_script=WORKER,
        modes=modes,
        proposal_payloads={"valid_proposal.json": VALID_PROPOSAL},
        name=name,
        worker_config=worker_config or {},
        policy=policy or _policy(),
    )


def _run_claims_task(
    tmp_path: Path, engine: SubprocessEngine
) -> tuple[ProjectRuntime, RuntimeResult]:
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="quota-test")
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="quota", existing_theme_ids=[]),
        engines=[engine],
    )
    return runtime, result


def _execution_report(
    runtime: ProjectRuntime, record: TaskAttemptRecord
) -> SubprocessExecutionResult:
    agent_result_path = runtime.project_root / record.agent_result_path
    agent_result = SubprocessAgentResult.model_validate(
        json.loads(agent_result_path.read_text(encoding="utf-8"))
    )
    return agent_result.execution_report


def _resource_limit_failures(record: TaskAttemptRecord) -> list[AttemptFailure]:
    return [
        failure
        for failure in record.detected_failures
        if failure.stage == AttemptFailureStage.RESOURCE_LIMIT
    ]


def _assert_breach_preserves_state(
    runtime: ProjectRuntime, result: RuntimeResult
) -> None:
    assert result.generation is None
    assert runtime.store.current_generation() == 0


@pytest.mark.parametrize(
    ("modes", "worker_config", "expected_code", "expected_path", "expected_message"),
    [
        (
            ("large_scratch_file",),
            {"scratch_file_bytes": 8 * 1024 * 1024},
            ResourceLimitCode.MAX_WRITABLE_SINGLE_FILE_BYTES,
            Path("scratch/big.bin"),
            "Writable file scratch/big.bin exceeded 4194304 bytes.",
        ),
        (
            ("too_many_files",),
            {"file_count": 300},
            ResourceLimitCode.MAX_WRITABLE_FILE_COUNT,
            Path("scratch"),
            "Writable file count exceeded 256.",
        ),
        (
            ("too_deep_tree",),
            {"tree_depth": 12},
            ResourceLimitCode.MAX_WRITABLE_DIRECTORY_DEPTH,
            Path("scratch", *(["d"] * 8)),
            "Writable directory depth exceeded 8.",
        ),
    ],
    ids=["large_scratch_file", "too_many_files", "too_deep_tree"],
)
def test_writable_quota_breach_fails_with_resource_limit_code(
    tmp_path, modes, worker_config, expected_code, expected_path, expected_message
):
    engine = _engine(
        f"fake-{expected_code}",
        modes,
        worker_config=worker_config,
        policy=_policy(),
    )
    runtime, result = _run_claims_task(tmp_path, engine)
    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    record = result.attempt_records[-1]
    assert record.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert not record.accepted_attempt
    breaches = _resource_limit_failures(record)
    assert len(breaches) == 1
    breach = breaches[0]
    assert breach.code == expected_code
    assert breach.message == expected_message
    assert breach.relative_path == expected_path
    # Modes that write no proposal also record a secondary proposal_missing.
    assert "proposal_missing" in {
        failure.code for failure in record.detected_failures
    }
    report = _execution_report(runtime, record)
    assert report.resource_limit_breached
    assert report.primary_outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    assert not report.timed_out
    _assert_breach_preserves_state(runtime, result)


def test_too_many_processes_exceeds_process_count_quota(tmp_path):
    policy = _policy(max_processes=4)
    engine = _engine(
        "fake-process-quota",
        ("too_many_processes",),
        worker_config={"process_count": 64},
        policy=policy,
    )
    runtime, result = _run_claims_task(tmp_path, engine)
    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    record = result.attempt_records[-1]
    assert record.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    breaches = _resource_limit_failures(record)
    assert len(breaches) == 1
    breach = breaches[0]
    assert breach.code == ResourceLimitCode.MAX_PROCESS_COUNT
    assert breach.message == "Process count exceeded 4."
    assert breach.relative_path is None
    report = _execution_report(runtime, record)
    assert report.resource_limit_breached
    assert report.primary_outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    # The monitor SIGKILLs the whole process group while the worker's
    # children are still alive; the worker never exits by itself.
    assert report.exit_code == -signal.SIGKILL
    assert not report.timed_out
    _assert_breach_preserves_state(runtime, result)


def test_tree_bytes_quota_triggers_below_single_file_cap(tmp_path):
    # The single-file cap is raised above the file size so the tree-byte
    # total is the quota that trips (single-file is checked first).
    policy = _policy(
        max_writable_single_file_bytes=32 * 1024 * 1024,
        max_writable_tree_bytes=8 * 1024 * 1024,
    )
    engine = _engine(
        "fake-tree-bytes",
        ("large_scratch_file",),
        worker_config={"scratch_file_bytes": 16 * 1024 * 1024},
        policy=policy,
    )
    runtime, result = _run_claims_task(tmp_path, engine)
    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    record = result.attempt_records[-1]
    breaches = _resource_limit_failures(record)
    assert len(breaches) == 1
    breach = breaches[0]
    assert breach.code == ResourceLimitCode.MAX_WRITABLE_TREE_BYTES
    assert breach.message == "Writable tree exceeded 8388608 bytes."
    assert breach.relative_path == Path("scratch")
    report = _execution_report(runtime, record)
    assert report.resource_limit_breached
    assert report.primary_outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    _assert_breach_preserves_state(runtime, result)


def test_breach_terminates_process_group_without_waiting_for_timeout(tmp_path):
    policy = _policy()
    # The worker writes the oversized scratch file and then sleeps for 60
    # seconds; the monitor must kill the process group, not wait it out.
    engine = _engine(
        "fake-group-kill",
        ("large_scratch_file", "timeout"),
        policy=policy,
    )
    runtime, result = _run_claims_task(tmp_path, engine)
    assert result.outcome is AttemptOutcome.ENGINE_RESOURCE_LIMIT_FAILURE
    record = result.attempt_records[-1]
    breaches = _resource_limit_failures(record)
    assert len(breaches) == 1
    assert breaches[0].code == ResourceLimitCode.MAX_WRITABLE_SINGLE_FILE_BYTES
    report = _execution_report(runtime, record)
    assert report.resource_limit_breached
    assert report.exit_code == -signal.SIGKILL
    assert not report.timed_out
    assert report.duration_seconds < policy.timeout_seconds
    _assert_breach_preserves_state(runtime, result)


def test_scratch_file_within_quota_is_permitted(tmp_path):
    policy = _policy()
    engine = _engine("fake-permitted-scratch", ("permitted_scratch",), policy=policy)
    runtime, result = _run_claims_task(tmp_path, engine)
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    assert runtime.store.current_generation() == 1
    record = result.attempt_records[-1]
    assert record.accepted_attempt
    assert record.detected_failures == ()
    report = _execution_report(runtime, record)
    assert not report.resource_limit_breached
    assert report.primary_outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    ok_txt = next(
        entry
        for entry in report.inventory
        if entry.relative_path == Path("scratch/ok.txt")
    )
    assert ok_txt.file_type == "regular"
    assert ok_txt.size_bytes == 1024
    assert ok_txt.size_bytes <= policy.max_writable_single_file_bytes
    assert ok_txt.content_hash is not None


def test_bundle_resource_larger_than_single_file_quota_is_permitted(tmp_path):
    policy = _policy()
    engine = _engine("fake-large-bundle", ("valid",), policy=policy)
    runtime = ProjectRuntime.create(tmp_path / "project", project_name="bundle-quota")
    document_dir = runtime.project_root / "input" / "deep_research"
    document_dir.mkdir(parents=True)
    document = document_dir / "survey.md"
    oversized = policy.max_writable_single_file_bytes + 1
    document.write_bytes(b"x" * oversized)
    result = runtime.run(
        TaskType.PARSE_DEEP_RESEARCH,
        ParseDeepResearchInvocation(topic="quota", document_paths=[document]),
        engines=[engine],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    assert runtime.store.current_generation() == 1
    record = result.attempt_records[-1]
    assert record.accepted_attempt
    assert record.detected_failures == ()
    # The task bundle and the per-attempt workspace copy really do contain a
    # resource file larger than the writable single-file quota.
    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    bundle_resource = (
        task_dir / "bundle" / "input" / "resources" / "RES0001" / "content.md"
    )
    assert bundle_resource.is_file()
    assert bundle_resource.stat().st_size == oversized
    assert oversized > policy.max_writable_single_file_bytes
    attempt_resource = (
        task_dir
        / "attempts"
        / record.attempt_id
        / "workspace"
        / "input"
        / "resources"
        / "RES0001"
        / "content.md"
    )
    assert attempt_resource.is_file()
    assert attempt_resource.stat().st_size == oversized
    report = _execution_report(runtime, record)
    assert not report.resource_limit_breached
    # The retained inventory only covers the writable quota roots; bundle/,
    # launcher/ and credentials/ are never scanned (§6.7).
    assert report.inventory
    assert {
        entry.relative_path.parts[0] for entry in report.inventory
    } <= set(WRITABLE_QUOTA_ROOTS)


def test_monitor_scans_only_writable_quota_roots(tmp_path):
    policy = _policy(max_writable_single_file_bytes=1024)
    oversized = policy.max_writable_single_file_bytes + 1
    for root_name in QUOTA_EXEMPT_ROOTS:
        root = tmp_path / root_name
        root.mkdir()
        (root / "oversized.bin").write_bytes(b"x" * oversized)
        deep = root
        for _ in range(policy.max_writable_directory_depth + 1):
            deep = deep / "d"
            deep.mkdir()
    for root_name in WRITABLE_QUOTA_ROOTS:
        (tmp_path / root_name).mkdir()
    assert scan_writable_roots(tmp_path, policy) is None
    target = tmp_path / "tmp" / "oversized.bin"
    target.write_bytes(b"x" * oversized)
    breach = scan_writable_roots(tmp_path, policy)
    assert breach is not None
    assert breach.code == ResourceLimitCode.MAX_WRITABLE_SINGLE_FILE_BYTES
    assert breach.relative_path == Path("tmp/oversized.bin")
    failure = breach.attempt_failure()
    assert failure.stage is AttemptFailureStage.RESOURCE_LIMIT
