from __future__ import annotations

import threading
from concurrent.futures import ThreadPoolExecutor

import pytest

from vibereview.models import CandidateClaim, ThemeRecord
from vibereview.runtime import (
    AssessClaimInput,
    AttemptOutcome,
    AuditPropositionInput,
    CandidateClaimProposal,
    ClaimAssessmentProposal,
    DiscoveryProposalBundle,
    GenerateCandidateClaimsInput,
    MockEngine,
    MockResponse,
    ProjectRuntime,
    RepositorySnapshot,
    RuntimeConfig,
    SemanticAuditProposal,
    TaskType,
    ThemeProposal,
)
from vibereview.runtime.dto import (
    GenerateRetrievalQueriesInput,
    RetrievalQueryProposalBundle,
)
from vibereview.runtime.promotion import promote_discovery


def _positive_proposal(label: str = "theme") -> DiscoveryProposalBundle:
    return DiscoveryProposalBundle(
        themes=[
            ThemeProposal(
                local_ref=f"{label}_1",
                title="Thermal management",
                description="Generated by deterministic fixture",
                origin="generated",
            )
        ],
        claims=[
            CandidateClaimProposal(
                local_ref=f"{label}_claim_1",
                theme_ref=f"{label}_1",
                candidate_claim="Preheating changes residual stress.",
                origin="generated",
                origin_refs=[],
            )
        ],
    )


def _create_empty_runtime(tmp_path, config=None) -> ProjectRuntime:
    return ProjectRuntime.create(
        tmp_path / "project",
        project_name="test",
        config=config,
    )


def _snapshot_without_downstream_claim_objects(bundle_factory) -> RepositorySnapshot:
    bundle = bundle_factory()
    for name in (
        "claim_assessments",
        "final_claim_validations",
        "claim_packets",
        "proposition_records",
        "semantic_audits",
        "rendered_sentences",
        "rendered_sentence_audits",
    ):
        bundle[name] = []
    return RepositorySnapshot.model_validate(bundle)


def _snapshot_ready_for_proposition_audit(bundle_factory) -> RepositorySnapshot:
    bundle = bundle_factory()
    bundle["rendered_sentences"] = []
    bundle["rendered_sentence_audits"] = []
    return RepositorySnapshot.model_validate(bundle)


def test_mock_engine_positive_result_is_canonicalized_and_advances(tmp_path):
    runtime = _create_empty_runtime(tmp_path)
    proposal = _positive_proposal()
    engine = MockEngine([MockResponse(proposal=proposal.model_dump(mode="json"))])
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[engine],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.transition is not None
    assert result.transition.canonicalized
    assert result.transition.downstream_eligible
    assert result.generation == 1
    assert result.allocated_ids == {"theme_1": "T0001", "theme_claim_1": "C0001"}
    _, snapshot, _ = runtime.store.load_current()
    assert snapshot.candidate_claims[0].claim_id == "C0001"
    task_dir = runtime.project_root / "work" / "tasks" / result.task_id
    assert (task_dir / "task_manifest.json").is_file()
    assert (task_dir / "accepted" / "proposal.json").is_file()
    assert (task_dir / "attempts" / "01-mock" / "attempt_record.json").is_file()


def test_compound_local_references_promote_to_canonical_graph(tmp_path):
    runtime = _create_empty_runtime(tmp_path)
    proposal = DiscoveryProposalBundle(
        themes=[
            ThemeProposal(
                local_ref="theme_1",
                title="Thermal management",
                description="parent",
                origin="human",
            ),
            ThemeProposal(
                local_ref="theme_2",
                title="Substrate preheating",
                description="child",
                origin="human",
                parent_ref="theme_1",
            ),
        ],
        claims=[
            CandidateClaimProposal(
                local_ref="claim_1",
                theme_ref="theme_2",
                candidate_claim="Preheating changes stress.",
                origin="human",
                origin_refs=[],
            )
        ],
    )
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[MockEngine([MockResponse(proposal=proposal.model_dump(mode="json"))])],
    )
    _, snapshot, _ = runtime.store.load_current()
    assert result.allocated_ids == {
        "theme_1": "T0001",
        "theme_2": "T0002",
        "claim_1": "C0001",
    }
    assert snapshot.themes[1].parent_theme_id == "T0001"
    assert snapshot.candidate_claims[0].theme_id == "T0002"


def test_valid_reject_is_canonicalized_without_fallback_or_claim_packet(
    tmp_path, bundle_factory
):
    snapshot = _snapshot_without_downstream_claim_objects(bundle_factory)
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="reject", initial_snapshot=snapshot
    )
    proposal = ClaimAssessmentProposal(
        claim_ref="C0001",
        aggregate_strength="low",
        evidence_sufficiency="insufficient",
        decision="REJECT",
        rejection_basis="insufficient_evidence",
        support_summary="Insufficient.",
        contradiction_summary="None.",
        qualification_summary="None.",
        reason="Evidence is insufficient.",
    )
    primary = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))], name="primary"
    )
    fallback = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))], name="fallback"
    )
    result = runtime.run(
        TaskType.ASSESS_CLAIM,
        AssessClaimInput(
            claim_id="C0001",
            claim_paper_evidence_ids=["CPE-C0001-P0001"],
        ),
        dependency_ids=["C0001", "CPE-C0001-P0001"],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.transition is not None
    assert result.transition.scientific_disposition == "REJECT"
    assert result.transition.canonicalized
    assert not result.transition.downstream_eligible
    assert primary.calls == 1
    assert fallback.calls == 0
    _, current, _ = runtime.store.load_current()
    assert current.claim_assessments[0].decision.value == "REJECT"
    assert current.claim_packets == ()


def test_valid_unsupported_audit_is_canonicalized_without_fallback(
    tmp_path, bundle_factory
):
    snapshot = _snapshot_ready_for_proposition_audit(bundle_factory)
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="audit", initial_snapshot=snapshot
    )
    proposal = SemanticAuditProposal(
        target_ref="PR0001",
        class_verdict="CORRECT",
        provenance_verdict="UNSUPPORTED",
        reason="The proposition is unsupported.",
        referenced_claim_refs=["C0001"],
        referenced_corpus_fact_refs=[],
        referenced_process_fact_refs=[],
    )
    primary = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))], name="primary"
    )
    fallback = MockEngine([], name="fallback")
    result = runtime.run(
        TaskType.AUDIT_PROPOSITION,
        AuditPropositionInput(proposition_id="PR0001"),
        dependency_ids=["PR0001"],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.transition is not None
    assert result.transition.scientific_disposition == "UNSUPPORTED"
    assert result.transition.canonicalized
    assert not result.transition.downstream_eligible
    assert fallback.calls == 0
    _, current, _ = runtime.store.load_current()
    assert len(current.semantic_audits) == 1
    assert current.semantic_audits[0].provenance_verdict.value == "UNSUPPORTED"


@pytest.mark.parametrize(
    ("response", "expected"),
    [
        (
            MockResponse(execution_error="engine unavailable"),
            AttemptOutcome.ENGINE_EXECUTION_FAILURE,
        ),
        (
            MockResponse(raw_output="not-json"),
            AttemptOutcome.ENGINE_FORMAT_FAILURE,
        ),
        (
            MockResponse(proposal={"themes": "wrong", "claims": []}),
            AttemptOutcome.ENGINE_SCHEMA_FAILURE,
        ),
        (
            MockResponse(
                proposal={
                    "themes": [],
                    "claims": [
                        {
                            "local_ref": "claim_1",
                            "theme_ref": "unknown_theme",
                            "candidate_claim": "Claim",
                            "origin": "generated",
                            "origin_refs": [],
                        }
                    ],
                }
            ),
            AttemptOutcome.ENGINE_PROPOSAL_VALIDATION_FAILURE,
        ),
    ],
)
def test_engine_attributable_failures_allow_fallback(tmp_path, response, expected):
    runtime = _create_empty_runtime(tmp_path)
    primary = MockEngine([response], name="primary")
    valid = _positive_proposal("fallback")
    fallback = MockEngine(
        [MockResponse(proposal=valid.model_dump(mode="json"))], name="fallback"
    )
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert [record.outcome for record in result.attempt_records] == [
        expected,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    assert primary.calls == 1
    assert fallback.calls == 1


def test_internal_runtime_failure_forbids_fallback(tmp_path, monkeypatch):
    runtime = _create_empty_runtime(tmp_path)
    proposal = _positive_proposal()
    primary = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))], name="primary"
    )
    fallback = MockEngine([], name="fallback")

    def fail(*args, **kwargs):
        raise RuntimeError("runtime bug")

    monkeypatch.setattr("vibereview.runtime.kernel.interpret_disposition", fail)
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.INTERNAL_RUNTIME_FAILURE
    assert fallback.calls == 0


def test_transaction_failure_forbids_fallback(tmp_path, monkeypatch):
    runtime = _create_empty_runtime(tmp_path)
    proposal = _positive_proposal()
    primary = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))], name="primary"
    )
    fallback = MockEngine([], name="fallback")

    def fail(**kwargs):
        raise OSError("disk failure")

    monkeypatch.setattr(runtime.store, "commit", fail)
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.TRANSACTION_FAILURE
    assert fallback.calls == 0


def test_contract_implementation_failure_forbids_fallback(tmp_path):
    runtime = _create_empty_runtime(tmp_path)
    proposal = RetrievalQueryProposalBundle(queries=[])
    primary = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))], name="primary"
    )
    fallback = MockEngine([], name="fallback")
    result = runtime.run(
        TaskType.GENERATE_RETRIEVAL_QUERIES,
        GenerateRetrievalQueriesInput(claim_ids=[]),
        dependency_ids=[],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.CONTRACT_IMPLEMENTATION_FAILURE
    assert fallback.calls == 0


def test_stale_snapshot_rebuilds_task_without_fallback(tmp_path):
    runtime = _create_empty_runtime(tmp_path)
    proposal = _positive_proposal("main")

    def concurrent_commit(task, call_number):
        if call_number == 0:
            generation = runtime.store.current_generation()
            runtime.store.commit(
                base_generation=generation,
                dependencies={},
                promotion=lambda snapshot, registry: promote_discovery(
                    snapshot,
                    registry,
                    DiscoveryProposalBundle(
                        themes=[
                            ThemeProposal(
                                local_ref="concurrent",
                                title="Concurrent",
                                description="state change",
                                origin="human",
                            )
                        ],
                        claims=[],
                    ),
                ),
            )

    primary = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))],
        name="primary",
        on_execute=concurrent_commit,
    )
    fallback = MockEngine([], name="fallback")
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.stale_rebuilds == 1
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.STALE_SNAPSHOT,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    assert primary.calls == 2
    assert fallback.calls == 0


def test_stale_rebuild_budget_is_finite(tmp_path):
    runtime = _create_empty_runtime(
        tmp_path,
        RuntimeConfig(max_stale_rebuilds=0, writer_lock_timeout_seconds=2),
    )
    proposal = _positive_proposal("main")

    def concurrent_commit(task, call_number):
        generation = runtime.store.current_generation()
        runtime.store.commit(
            base_generation=generation,
            dependencies={},
            promotion=lambda snapshot, registry: promote_discovery(
                snapshot,
                registry,
                DiscoveryProposalBundle(
                    themes=[
                        ThemeProposal(
                            local_ref=f"change_{call_number}",
                            title="Change",
                            description="forces staleness",
                            origin="human",
                        )
                    ],
                    claims=[],
                ),
            ),
        )

    primary = MockEngine(
        [MockResponse(proposal=proposal.model_dump(mode="json"))],
        name="primary",
        on_execute=concurrent_commit,
    )
    fallback = MockEngine([], name="fallback")
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[primary, fallback],
    )
    assert result.outcome is AttemptOutcome.STALE_SNAPSHOT
    assert primary.calls == 1
    assert fallback.calls == 0


def test_technical_retry_budget_is_finite_and_precedes_fallback(tmp_path):
    runtime = _create_empty_runtime(
        tmp_path,
        RuntimeConfig(
            technical_attempts_per_engine=2,
            max_fallback_engines=1,
            writer_lock_timeout_seconds=2,
        ),
    )
    proposal = _positive_proposal("retry")
    primary = MockEngine(
        [
            MockResponse(execution_error="temporary failure"),
            MockResponse(proposal=proposal.model_dump(mode="json")),
        ],
        name="primary",
    )
    fallback = MockEngine([], name="fallback")
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[]),
        dependency_ids=[],
        engines=[primary, fallback],
    )
    assert [record.outcome for record in result.attempt_records] == [
        AttemptOutcome.ENGINE_EXECUTION_FAILURE,
        AttemptOutcome.VALID_SCIENTIFIC_RESULT,
    ]
    assert primary.calls == 2
    assert fallback.calls == 0


def test_cache_hit_is_revalidated_without_engine_execution(tmp_path):
    runtime = _create_empty_runtime(tmp_path)
    proposal = _positive_proposal("cached")
    engine = MockEngine([MockResponse(proposal=proposal.model_dump(mode="json"))])
    input_dto = GenerateCandidateClaimsInput(topic="stress", existing_theme_ids=[])
    first = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        input_dto,
        dependency_ids=[],
        engines=[engine],
    )
    second = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        input_dto,
        dependency_ids=[],
        engines=[engine],
    )
    assert first.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert second.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert engine.calls == 1


def test_concurrent_tasks_allocate_canonical_ids_without_collision(tmp_path):
    initial = RepositorySnapshot(
        themes=(
            ThemeRecord(
                theme_id="T0001",
                title="Existing",
                description="existing",
                origin="human",
                parent_theme_id=None,
            ),
        ),
        candidate_claims=(
            CandidateClaim(
                claim_id="C0040",
                theme_id="T0001",
                candidate_claim="Existing claim",
                origin="human",
                origin_refs=[],
            ),
        ),
    )
    runtime = ProjectRuntime.create(
        tmp_path / "project", project_name="concurrent", initial_snapshot=initial
    )
    barrier = threading.Barrier(2)

    def response(prefix):
        return DiscoveryProposalBundle(
            themes=[],
            claims=[
                CandidateClaimProposal(
                    local_ref=f"{prefix}_{index}",
                    theme_ref="T0001",
                    candidate_claim=f"Claim {prefix} {index}",
                    origin="generated",
                    origin_refs=[],
                )
                for index in range(1, 4)
            ],
        )

    def engine(prefix):
        def synchronize(task, call_number):
            if call_number == 0:
                barrier.wait(timeout=2)

        proposal = response(prefix)
        return MockEngine(
            [MockResponse(proposal=proposal.model_dump(mode="json"))],
            name=f"mock-{prefix}",
            on_execute=synchronize,
        )

    def run(prefix):
        return runtime.run(
            TaskType.GENERATE_CANDIDATE_CLAIMS,
            GenerateCandidateClaimsInput(
                topic=f"topic-{prefix}", existing_theme_ids=["T0001"]
            ),
            dependency_ids=["T0001"],
            engines=[engine(prefix)],
        )

    with ThreadPoolExecutor(max_workers=2) as executor:
        results = list(executor.map(run, ["a", "b"]))

    allocated = {
        value
        for result in results
        for key, value in result.allocated_ids.items()
        if key.startswith(("a_", "b_"))
    }
    assert allocated == {f"C{number:04d}" for number in range(41, 47)}
    assert all(result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT for result in results)
    _, snapshot, _ = runtime.store.load_current()
    assert {claim.claim_id for claim in snapshot.candidate_claims} == {
        "C0040",
        *allocated,
    }
