"""Bounded stream-capture conformance (goal.md §7.6, §6.8, §7.14).

The deterministic fake worker floods stdout and stderr through the real
subprocess boundary; the runtime must drain both streams concurrently without
deadlock while retaining only the configured bounded, redacted bytes. Every
``DiagnosticCapture`` must describe the exact persisted ``attempt/stdout.txt``
/ ``attempt/stderr.txt`` file and never the unredacted secret-bearing stream.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from vibereview.runtime import (
    AttemptOutcome,
    DiagnosticCapture,
    GenerateCandidateClaimsInvocation,
    ProjectRuntime,
    SubprocessAgentResult,
    SubprocessEngine,
    SubprocessExecutionResult,
    SyntheticCredentialProvider,
    TaskType,
    deterministic_test_policy,
)
from vibereview.runtime.records import TaskAttemptRecord

WORKER = Path(__file__).resolve().parent.parent / "helpers" / "fake_agent.py"

STREAM_BYTES = 10 * 1024 * 1024
SMALL_STREAM_BYTES = 1024
REDACTED_PLACEHOLDER = b"[REDACTED]"
SECRET_VALUE = "vibereview-test-secret-9c27fa4e"

CAPTURE_FIELDS = (
    "relative_path",
    "bytes_observed",
    "bytes_retained",
    "truncated",
    "retained_redacted_hash",
    "redactions_applied",
)


def _valid_proposal_bytes() -> bytes:
    payload = {
        "themes": [
            {
                "local_ref": "theme_1",
                "title": "Thermal management",
                "description": "Generated by deterministic fixture",
                "origin": "generated",
                "parent_ref": None,
            }
        ],
        "claims": [
            {
                "local_ref": "claim_1",
                "theme_ref": "theme_1",
                "candidate_claim": "Preheating changes residual stress.",
                "origin": "generated",
                "origin_refs": [],
            }
        ],
    }
    return json.dumps(payload).encode("utf-8")


def _engine(
    name: str,
    modes: tuple[str, ...],
    *,
    worker_config: dict | None = None,
    credential_provider: SyntheticCredentialProvider | None = None,
) -> SubprocessEngine:
    return SubprocessEngine(
        worker_script=WORKER,
        modes=modes,
        worker_config=worker_config or {},
        proposal_payloads={"valid_proposal.json": _valid_proposal_bytes()},
        policy=deterministic_test_policy(),
        credential_provider=credential_provider,
        name=name,
    )


def _run_claims_task(tmp_path: Path, engine: SubprocessEngine, project_name: str):
    runtime = ProjectRuntime.create(tmp_path / "project", project_name=project_name)
    result = runtime.run(
        TaskType.GENERATE_CANDIDATE_CLAIMS,
        GenerateCandidateClaimsInvocation(topic="stress", existing_theme_ids=[]),
        engines=[engine],
    )
    return runtime, result


def _attempt_dir(runtime: ProjectRuntime, record: TaskAttemptRecord) -> Path:
    attempt_dir = (runtime.project_root / record.agent_result_path).parent
    assert attempt_dir.is_dir()
    return attempt_dir


def _execution_report(
    runtime: ProjectRuntime, record: TaskAttemptRecord
) -> SubprocessExecutionResult:
    agent_result_path = runtime.project_root / record.agent_result_path
    agent_result = SubprocessAgentResult.model_validate_json(
        agent_result_path.read_text(encoding="utf-8")
    )
    return agent_result.execution_report


def _assert_capture_matches_persisted_file(
    capture: DiagnosticCapture, persisted: Path
) -> None:
    """§6.8: the capture describes the exact persisted diagnostic file."""

    assert persisted.is_file()
    payload = persisted.read_bytes()
    assert capture.relative_path == Path("attempt") / persisted.name
    assert capture.retained_redacted_hash == (
        "sha256:" + hashlib.sha256(payload).hexdigest()
    )
    assert capture.bytes_retained == len(payload)
    assert capture.bytes_retained == persisted.stat().st_size


def test_ten_mebibyte_streams_stay_bounded_without_deadlock(tmp_path):
    policy = deterministic_test_policy()
    engine = _engine(
        "fake-diagnostics-large",
        ("large_stdout", "large_stderr", "valid"),
        worker_config={"stream_bytes": STREAM_BYTES},
    )
    runtime, result = _run_claims_task(tmp_path, engine, "diagnostics-large")

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    assert len(result.attempt_records) == 1
    record = result.attempt_records[0]
    report = _execution_report(runtime, record)

    # No deadlock: a worker blocked on a full pipe could only finish through
    # the timeout path.
    assert report.launch_error is None
    assert report.timed_out is False
    assert report.exit_code == 0
    assert report.duration_seconds < policy.timeout_seconds
    assert report.primary_outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT

    assert tuple(DiagnosticCapture.model_fields) == CAPTURE_FIELDS
    attempt_dir = _attempt_dir(runtime, record)
    for capture, filename, bound in (
        (report.stdout_capture, "stdout.txt", policy.max_stdout_bytes),
        (report.stderr_capture, "stderr.txt", policy.max_stderr_bytes),
    ):
        assert capture.bytes_observed >= STREAM_BYTES
        assert capture.bytes_retained <= bound
        assert capture.truncated is True
        assert capture.redactions_applied == 0
        assert DiagnosticCapture.model_validate(capture.model_dump()) == capture
        _assert_capture_matches_persisted_file(capture, attempt_dir / filename)


def test_small_stream_is_untruncated_and_fully_retained(tmp_path):
    engine = _engine(
        "fake-diagnostics-small",
        ("large_stdout", "valid"),
        worker_config={"stream_bytes": SMALL_STREAM_BYTES},
    )
    runtime, result = _run_claims_task(tmp_path, engine, "diagnostics-small")

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    record = result.attempt_records[0]
    report = _execution_report(runtime, record)
    attempt_dir = _attempt_dir(runtime, record)

    stdout_capture = report.stdout_capture
    assert stdout_capture.bytes_observed == SMALL_STREAM_BYTES
    assert stdout_capture.bytes_retained == SMALL_STREAM_BYTES
    assert stdout_capture.truncated is False
    _assert_capture_matches_persisted_file(stdout_capture, attempt_dir / "stdout.txt")

    stderr_capture = report.stderr_capture
    assert stderr_capture.bytes_observed == 0
    assert stderr_capture.bytes_retained == 0
    assert stderr_capture.truncated is False
    _assert_capture_matches_persisted_file(stderr_capture, attempt_dir / "stderr.txt")


def test_no_api_records_hash_of_unredacted_stream(tmp_path):
    provider = SyntheticCredentialProvider(
        secret_env={"VIBEREVIEW_INJECTED_SECRET": SECRET_VALUE}
    )
    engine = _engine(
        "fake-diagnostics-secret",
        ("injected_secret_probe", "valid"),
        credential_provider=provider,
    )
    runtime, result = _run_claims_task(tmp_path, engine, "diagnostics-secret")

    assert result.outcome is AttemptOutcome.VALID_SCIENTIFIC_RESULT
    assert result.generation == 1
    record = result.attempt_records[0]
    report = _execution_report(runtime, record)
    attempt_dir = _attempt_dir(runtime, record)

    unredacted_stream = f"INJECTED_SECRET={SECRET_VALUE}\n".encode("utf-8")
    unredacted_hash = "sha256:" + hashlib.sha256(unredacted_stream).hexdigest()

    stdout_capture = report.stdout_capture
    persisted_stdout = (attempt_dir / "stdout.txt").read_bytes()
    assert stdout_capture.bytes_observed == len(unredacted_stream)
    assert stdout_capture.bytes_retained != stdout_capture.bytes_observed
    assert stdout_capture.redactions_applied == 1
    assert SECRET_VALUE.encode("utf-8") not in persisted_stdout
    assert REDACTED_PLACEHOLDER in persisted_stdout
    _assert_capture_matches_persisted_file(stdout_capture, attempt_dir / "stdout.txt")
    _assert_capture_matches_persisted_file(report.stderr_capture, attempt_dir / "stderr.txt")

    # The recorded hash covers the persisted redacted file, never the raw
    # secret-bearing stream (goal.md §6.8).
    assert stdout_capture.retained_redacted_hash != unredacted_hash
    assert report.stderr_capture.retained_redacted_hash != unredacted_hash

    # No persisted artifact anywhere in the project contains the unredacted
    # stream digest or the secret itself.
    secret_bytes = SECRET_VALUE.encode("utf-8")
    unredacted_digest = unredacted_hash.encode("ascii")
    for path in runtime.project_root.rglob("*"):
        if not path.is_file():
            continue
        content = path.read_bytes()
        assert unredacted_digest not in content, path
        assert secret_bytes not in content, path
