"""Public Phase-0 API for VibeReviewPaper."""

from .errors import RepositoryValidationError, ValidationIssue, ValidationReport
from .ids import candidate_claim_hash, normalize_doi
from .models import (
    CandidateClaim,
    CitationBinding,
    ClaimAssessment,
    ClaimPacket,
    ClaimPaperEvidence,
    CorpusFact,
    EvidenceRecord,
    FinalClaimValidation,
    Paper,
    PropositionRecord,
    RenderedSentence,
    RenderedSentenceAudit,
    RetrievalDisposition,
    RetrievalQuery,
    RetrievedSpan,
    ReviewProcessFact,
    SemanticAuditResult,
    ThemeRecord,
)
from .validators import (
    derive_semantic_audit_disposition,
    validate_claim_bundle,
    validate_claim_evidence_bundle,
    validate_evidence_bundle,
    validate_identity_registry,
    validate_proposition_bundle,
    validate_rendered_prose_bundle,
    validate_repository,
    validate_retrieval_bundle,
    validate_theme_hierarchy,
)

__all__ = [
    "CandidateClaim",
    "CitationBinding",
    "ClaimAssessment",
    "ClaimPacket",
    "ClaimPaperEvidence",
    "CorpusFact",
    "EvidenceRecord",
    "FinalClaimValidation",
    "Paper",
    "PropositionRecord",
    "RenderedSentence",
    "RenderedSentenceAudit",
    "RepositoryValidationError",
    "RetrievalDisposition",
    "RetrievalQuery",
    "RetrievedSpan",
    "ReviewProcessFact",
    "SemanticAuditResult",
    "ThemeRecord",
    "ValidationIssue",
    "ValidationReport",
    "candidate_claim_hash",
    "derive_semantic_audit_disposition",
    "normalize_doi",
    "validate_claim_bundle",
    "validate_claim_evidence_bundle",
    "validate_evidence_bundle",
    "validate_identity_registry",
    "validate_proposition_bundle",
    "validate_rendered_prose_bundle",
    "validate_repository",
    "validate_retrieval_bundle",
    "validate_theme_hierarchy",
]
